import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for ChatCompletionMessageListDataInner
void main() {
  final instance = ChatCompletionMessageListDataInnerBuilder();
  // TODO add properties to the builder and call build()

  group(ChatCompletionMessageListDataInner, () {
    // The contents of the message.
    // String content
    test('to test the property `content`', () async {
      // TODO
    });

    // The refusal message generated by the model.
    // String refusal
    test('to test the property `refusal`', () async {
      // TODO
    });

    // The tool calls generated by the model, such as function calls.
    // BuiltList<ChatCompletionMessageToolCall> toolCalls
    test('to test the property `toolCalls`', () async {
      // TODO
    });

    // Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
    // BuiltList<ChatCompletionResponseMessageAnnotationsInner> annotations
    test('to test the property `annotations`', () async {
      // TODO
    });

    // The role of the author of this message.
    // String role
    test('to test the property `role`', () async {
      // TODO
    });

    // ChatCompletionResponseMessageFunctionCall functionCall
    test('to test the property `functionCall`', () async {
      // TODO
    });

    // ChatCompletionResponseMessageAudio audio
    test('to test the property `audio`', () async {
      // TODO
    });

    // The identifier of the chat message.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

  });
}
