import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for ChatCompletionRequestAssistantMessageContentPart
void main() {
  final instance = ChatCompletionRequestAssistantMessageContentPartBuilder();
  // TODO add properties to the builder and call build()

  group(ChatCompletionRequestAssistantMessageContentPart, () {
    // The type of the content part.
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The text content.
    // String text
    test('to test the property `text`', () async {
      // TODO
    });

    // The refusal message generated by the model.
    // String refusal
    test('to test the property `refusal`', () async {
      // TODO
    });

  });
}
