//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openai_flutter_sdk/api.dart';
import 'package:test/test.dart';

// tests for CodeInterpreterToolCall
void main() {
  // final instance = CodeInterpreterToolCall();

  group('test CodeInterpreterToolCall', () {
    // The type of the code interpreter tool call. Always `code_interpreter_call`. 
    // String type (default value: 'code_interpreter_call')
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the code interpreter tool call. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The status of the code interpreter tool call. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });

    // The ID of the container used to run the code. 
    // String containerId
    test('to test the property `containerId`', () async {
      // TODO
    });

    // The code to run, or null if not available. 
    // String code
    test('to test the property `code`', () async {
      // TODO
    });

    // The outputs generated by the code interpreter, such as logs or images.  Can be null if no outputs are available. 
    // List<CodeInterpreterToolCallOutputsInner> outputs (default value: const [])
    test('to test the property `outputs`', () async {
      // TODO
    });


  });

}
