import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for CodeInterpreterToolCall
void main() {
  final instance = CodeInterpreterToolCallBuilder();
  // TODO add properties to the builder and call build()

  group(CodeInterpreterToolCall, () {
    // The type of the code interpreter tool call. Always `code_interpreter_call`. 
    // String type (default value: 'code_interpreter_call')
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the code interpreter tool call. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The status of the code interpreter tool call. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });

    // The ID of the container used to run the code. 
    // String containerId
    test('to test the property `containerId`', () async {
      // TODO
    });

    // The code to run, or null if not available. 
    // String code
    test('to test the property `code`', () async {
      // TODO
    });

    // The outputs generated by the code interpreter, such as logs or images.  Can be null if no outputs are available. 
    // BuiltList<CodeInterpreterToolCallOutputsInner> outputs
    test('to test the property `outputs`', () async {
      // TODO
    });

  });
}
