import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for CreateMessageRequest
void main() {
  final instance = CreateMessageRequestBuilder();
  // TODO add properties to the builder and call build()

  group(CreateMessageRequest, () {
    // The role of the entity that is creating the message. Allowed values include: - `user`: Indicates the message is sent by an actual user and should be used in most cases to represent user-generated messages. - `assistant`: Indicates the message is generated by the assistant. Use this value to insert messages from the assistant into the conversation. 
    // String role
    test('to test the property `role`', () async {
      // TODO
    });

    // CreateMessageRequestContent content
    test('to test the property `content`', () async {
      // TODO
    });

    // A list of files attached to the message, and the tools they should be added to.
    // BuiltList<CreateMessageRequestAttachmentsInner> attachments
    test('to test the property `attachments`', () async {
      // TODO
    });

    // Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard.   Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters. 
    // BuiltMap<String, String> metadata
    test('to test the property `metadata`', () async {
      // TODO
    });

  });
}
