import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for FineTuneReinforcementRequestInputMessagesInner
void main() {
  final instance = FineTuneReinforcementRequestInputMessagesInnerBuilder();
  // TODO add properties to the builder and call build()

  group(FineTuneReinforcementRequestInputMessagesInner, () {
    // ChatCompletionRequestToolMessageContent content
    test('to test the property `content`', () async {
      // TODO
    });

    // The role of the messages author, in this case `tool`.
    // String role
    test('to test the property `role`', () async {
      // TODO
    });

    // An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    // String name
    test('to test the property `name`', () async {
      // TODO
    });

    // Controls whether the assistant message is trained against (0 or 1)
    // int weight
    test('to test the property `weight`', () async {
      // TODO
    });

    // The refusal message by the assistant.
    // String refusal
    test('to test the property `refusal`', () async {
      // TODO
    });

    // ChatCompletionRequestAssistantMessageAudio audio
    test('to test the property `audio`', () async {
      // TODO
    });

    // The tool calls generated by the model, such as function calls.
    // BuiltList<ChatCompletionMessageToolCall> toolCalls
    test('to test the property `toolCalls`', () async {
      // TODO
    });

    // ChatCompletionRequestAssistantMessageFunctionCall functionCall
    test('to test the property `functionCall`', () async {
      // TODO
    });

    // Tool call that this message is responding to.
    // String toolCallId
    test('to test the property `toolCallId`', () async {
      // TODO
    });

  });
}
