import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for FunctionToolCall
void main() {
  //final instance = FunctionToolCallBuilder();
  // TODO add properties to the builder and call build()

  group(FunctionToolCall, () {
    // The unique ID of the function tool call. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The type of the function tool call. Always `function_call`. 
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the function tool call generated by the model. 
    // String callId
    test('to test the property `callId`', () async {
      // TODO
    });

    // The name of the function to run. 
    // String name
    test('to test the property `name`', () async {
      // TODO
    });

    // A JSON string of the arguments to pass to the function. 
    // String arguments
    test('to test the property `arguments`', () async {
      // TODO
    });

    // The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });

  });
}
