//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openai_flutter_sdk/api.dart';
import 'package:test/test.dart';

// tests for FunctionToolCall
void main() {
  // final instance = FunctionToolCall();

  group('test FunctionToolCall', () {
    // The unique ID of the function tool call. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The type of the function tool call. Always `function_call`. 
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the function tool call generated by the model. 
    // String callId
    test('to test the property `callId`', () async {
      // TODO
    });

    // The name of the function to run. 
    // String name
    test('to test the property `name`', () async {
      // TODO
    });

    // A JSON string of the arguments to pass to the function. 
    // String arguments
    test('to test the property `arguments`', () async {
      // TODO
    });

    // The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });


  });

}
