import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for FunctionToolCallOutput
void main() {
  //final instance = FunctionToolCallOutputBuilder();
  // TODO add properties to the builder and call build()

  group(FunctionToolCallOutput, () {
    // The unique ID of the function tool call output. Populated when this item is returned via API. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The type of the function tool call output. Always `function_call_output`. 
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the function tool call generated by the model. 
    // String callId
    test('to test the property `callId`', () async {
      // TODO
    });

    // A JSON string of the output of the function tool call. 
    // String output
    test('to test the property `output`', () async {
      // TODO
    });

    // The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });

  });
}
