import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for LocalShellToolCallOutput
void main() {
  final instance = LocalShellToolCallOutputBuilder();
  // TODO add properties to the builder and call build()

  group(LocalShellToolCallOutput, () {
    // The type of the local shell tool call output. Always `local_shell_call_output`. 
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the local shell tool call generated by the model. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // A JSON string of the output of the local shell tool call. 
    // String output
    test('to test the property `output`', () async {
      // TODO
    });

    // The status of the item. One of `in_progress`, `completed`, or `incomplete`. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });

  });
}
