//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openai_flutter_sdk/api.dart';
import 'package:test/test.dart';

// tests for LocalShellToolCallOutput
void main() {
  // final instance = LocalShellToolCallOutput();

  group('test LocalShellToolCallOutput', () {
    // The type of the local shell tool call output. Always `local_shell_call_output`. 
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the local shell tool call generated by the model. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // A JSON string of the output of the local shell tool call. 
    // String output
    test('to test the property `output`', () async {
      // TODO
    });

    // The status of the item. One of `in_progress`, `completed`, or `incomplete`. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });


  });

}
