//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openai_flutter_sdk/api.dart';
import 'package:test/test.dart';

// tests for LocalShellToolCall
void main() {
  // final instance = LocalShellToolCall();

  group('test LocalShellToolCall', () {
    // The type of the local shell call. Always `local_shell_call`. 
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the local shell call. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The unique ID of the local shell tool call generated by the model. 
    // String callId
    test('to test the property `callId`', () async {
      // TODO
    });

    // LocalShellExecAction action
    test('to test the property `action`', () async {
      // TODO
    });

    // The status of the local shell call. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });


  });

}
