import 'package:test/test.dart';
import 'package:openai_flutter_sdk/openai_flutter_sdk.dart';

// tests for LocalShellToolCall
void main() {
  final instance = LocalShellToolCallBuilder();
  // TODO add properties to the builder and call build()

  group(LocalShellToolCall, () {
    // The type of the local shell call. Always `local_shell_call`. 
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The unique ID of the local shell call. 
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The unique ID of the local shell tool call generated by the model. 
    // String callId
    test('to test the property `callId`', () async {
      // TODO
    });

    // LocalShellExecAction action
    test('to test the property `action`', () async {
      // TODO
    });

    // The status of the local shell call. 
    // String status
    test('to test the property `status`', () async {
      // TODO
    });

  });
}
