//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:openai_flutter_sdk/src/model/chat_completion_response_message_audio.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_response_message_function_call.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_response_message.dart';
import 'package:built_collection/built_collection.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_response_message_annotations_inner.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_message_tool_call.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'chat_completion_message_list_data_inner.g.dart';

/// ChatCompletionMessageListDataInner
///
/// Properties:
/// * [content] - The contents of the message.
/// * [refusal] - The refusal message generated by the model.
/// * [toolCalls] - The tool calls generated by the model, such as function calls.
/// * [annotations] - Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
/// * [role] - The role of the author of this message.
/// * [functionCall] 
/// * [audio] 
/// * [id] - The identifier of the chat message.
@BuiltValue()
abstract class ChatCompletionMessageListDataInner implements ChatCompletionResponseMessage, Built<ChatCompletionMessageListDataInner, ChatCompletionMessageListDataInnerBuilder> {
  /// The identifier of the chat message.
  @BuiltValueField(wireName: r'id')
  String get id;

  ChatCompletionMessageListDataInner._();

  factory ChatCompletionMessageListDataInner([void updates(ChatCompletionMessageListDataInnerBuilder b)]) = _$ChatCompletionMessageListDataInner;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(ChatCompletionMessageListDataInnerBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<ChatCompletionMessageListDataInner> get serializer => _$ChatCompletionMessageListDataInnerSerializer();
}

class _$ChatCompletionMessageListDataInnerSerializer implements PrimitiveSerializer<ChatCompletionMessageListDataInner> {
  @override
  final Iterable<Type> types = const [ChatCompletionMessageListDataInner, _$ChatCompletionMessageListDataInner];

  @override
  final String wireName = r'ChatCompletionMessageListDataInner';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    ChatCompletionMessageListDataInner object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'role';
    yield serializers.serialize(
      object.role,
      specifiedType: const FullType(ChatCompletionResponseMessageRoleEnum),
    );
    if (object.functionCall != null) {
      yield r'function_call';
      yield serializers.serialize(
        object.functionCall,
        specifiedType: const FullType(ChatCompletionResponseMessageFunctionCall),
      );
    }
    yield r'refusal';
    yield serializers.serialize(
      object.refusal,
      specifiedType: const FullType(String),
    );
    if (object.annotations != null) {
      yield r'annotations';
      yield serializers.serialize(
        object.annotations,
        specifiedType: const FullType(BuiltList, [FullType(ChatCompletionResponseMessageAnnotationsInner)]),
      );
    }
    yield r'id';
    yield serializers.serialize(
      object.id,
      specifiedType: const FullType(String),
    );
    if (object.audio != null) {
      yield r'audio';
      yield serializers.serialize(
        object.audio,
        specifiedType: const FullType(ChatCompletionResponseMessageAudio),
      );
    }
    if (object.toolCalls != null) {
      yield r'tool_calls';
      yield serializers.serialize(
        object.toolCalls,
        specifiedType: const FullType(BuiltList, [FullType(ChatCompletionMessageToolCall)]),
      );
    }
    yield r'content';
    yield serializers.serialize(
      object.content,
      specifiedType: const FullType(String),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    ChatCompletionMessageListDataInner object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required ChatCompletionMessageListDataInnerBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'role':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(ChatCompletionResponseMessageRoleEnum),
          ) as ChatCompletionResponseMessageRoleEnum;
          result.role = valueDes;
          break;
        case r'function_call':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(ChatCompletionResponseMessageFunctionCall),
          ) as ChatCompletionResponseMessageFunctionCall;
          result.functionCall.replace(valueDes);
          break;
        case r'refusal':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.refusal = valueDes;
          break;
        case r'annotations':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(BuiltList, [FullType(ChatCompletionResponseMessageAnnotationsInner)]),
          ) as BuiltList<ChatCompletionResponseMessageAnnotationsInner>;
          result.annotations.replace(valueDes);
          break;
        case r'id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.id = valueDes;
          break;
        case r'audio':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(ChatCompletionResponseMessageAudio),
          ) as ChatCompletionResponseMessageAudio;
          result.audio.replace(valueDes);
          break;
        case r'tool_calls':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(BuiltList, [FullType(ChatCompletionMessageToolCall)]),
          ) as BuiltList<ChatCompletionMessageToolCall>;
          result.toolCalls.replace(valueDes);
          break;
        case r'content':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.content = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  ChatCompletionMessageListDataInner deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = ChatCompletionMessageListDataInnerBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class ChatCompletionMessageListDataInnerRoleEnum extends EnumClass {

  /// The role of the author of this message.
  @BuiltValueEnumConst(wireName: r'assistant')
  static const ChatCompletionMessageListDataInnerRoleEnum assistant = _$chatCompletionMessageListDataInnerRoleEnum_assistant;

  static Serializer<ChatCompletionMessageListDataInnerRoleEnum> get serializer => _$chatCompletionMessageListDataInnerRoleEnumSerializer;

  const ChatCompletionMessageListDataInnerRoleEnum._(String name): super(name);

  static BuiltSet<ChatCompletionMessageListDataInnerRoleEnum> get values => _$chatCompletionMessageListDataInnerRoleEnumValues;
  static ChatCompletionMessageListDataInnerRoleEnum valueOf(String name) => _$chatCompletionMessageListDataInnerRoleEnumValueOf(name);
}

