//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:openai_flutter_sdk/src/model/chat_completion_response_message_audio.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_response_message_function_call.dart';
import 'package:built_collection/built_collection.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_response_message_annotations_inner.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_message_tool_call.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'chat_completion_response_message.g.dart';

/// A chat completion message generated by the model.
///
/// Properties:
/// * [content] - The contents of the message.
/// * [refusal] - The refusal message generated by the model.
/// * [toolCalls] - The tool calls generated by the model, such as function calls.
/// * [annotations] - Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
/// * [role] - The role of the author of this message.
/// * [functionCall] 
/// * [audio] 
@BuiltValue(instantiable: false)
abstract class ChatCompletionResponseMessage  {
  /// The contents of the message.
  @BuiltValueField(wireName: r'content')
  String get content;

  /// The refusal message generated by the model.
  @BuiltValueField(wireName: r'refusal')
  String get refusal;

  /// The tool calls generated by the model, such as function calls.
  @BuiltValueField(wireName: r'tool_calls')
  BuiltList<ChatCompletionMessageToolCall>? get toolCalls;

  /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
  @BuiltValueField(wireName: r'annotations')
  BuiltList<ChatCompletionResponseMessageAnnotationsInner>? get annotations;

  /// The role of the author of this message.
  @BuiltValueField(wireName: r'role')
  ChatCompletionResponseMessageRoleEnum get role;
  // enum roleEnum {  assistant,  };

  @Deprecated('functionCall has been deprecated')
  @BuiltValueField(wireName: r'function_call')
  ChatCompletionResponseMessageFunctionCall? get functionCall;

  @BuiltValueField(wireName: r'audio')
  ChatCompletionResponseMessageAudio? get audio;

  @BuiltValueSerializer(custom: true)
  static Serializer<ChatCompletionResponseMessage> get serializer => _$ChatCompletionResponseMessageSerializer();
}

class _$ChatCompletionResponseMessageSerializer implements PrimitiveSerializer<ChatCompletionResponseMessage> {
  @override
  final Iterable<Type> types = const [ChatCompletionResponseMessage];

  @override
  final String wireName = r'ChatCompletionResponseMessage';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    ChatCompletionResponseMessage object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'content';
    yield serializers.serialize(
      object.content,
      specifiedType: const FullType(String),
    );
    yield r'refusal';
    yield serializers.serialize(
      object.refusal,
      specifiedType: const FullType(String),
    );
    if (object.toolCalls != null) {
      yield r'tool_calls';
      yield serializers.serialize(
        object.toolCalls,
        specifiedType: const FullType(BuiltList, [FullType(ChatCompletionMessageToolCall)]),
      );
    }
    if (object.annotations != null) {
      yield r'annotations';
      yield serializers.serialize(
        object.annotations,
        specifiedType: const FullType(BuiltList, [FullType(ChatCompletionResponseMessageAnnotationsInner)]),
      );
    }
    yield r'role';
    yield serializers.serialize(
      object.role,
      specifiedType: const FullType(ChatCompletionResponseMessageRoleEnum),
    );
    if (object.functionCall != null) {
      yield r'function_call';
      yield serializers.serialize(
        object.functionCall,
        specifiedType: const FullType(ChatCompletionResponseMessageFunctionCall),
      );
    }
    if (object.audio != null) {
      yield r'audio';
      yield serializers.serialize(
        object.audio,
        specifiedType: const FullType(ChatCompletionResponseMessageAudio),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    ChatCompletionResponseMessage object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  @override
  ChatCompletionResponseMessage deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return serializers.deserialize(serialized, specifiedType: FullType($ChatCompletionResponseMessage)) as $ChatCompletionResponseMessage;
  }
}

/// a concrete implementation of [ChatCompletionResponseMessage], since [ChatCompletionResponseMessage] is not instantiable
@BuiltValue(instantiable: true)
abstract class $ChatCompletionResponseMessage implements ChatCompletionResponseMessage, Built<$ChatCompletionResponseMessage, $ChatCompletionResponseMessageBuilder> {
  $ChatCompletionResponseMessage._();

  factory $ChatCompletionResponseMessage([void Function($ChatCompletionResponseMessageBuilder)? updates]) = _$$ChatCompletionResponseMessage;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults($ChatCompletionResponseMessageBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<$ChatCompletionResponseMessage> get serializer => _$$ChatCompletionResponseMessageSerializer();
}

class _$$ChatCompletionResponseMessageSerializer implements PrimitiveSerializer<$ChatCompletionResponseMessage> {
  @override
  final Iterable<Type> types = const [$ChatCompletionResponseMessage, _$$ChatCompletionResponseMessage];

  @override
  final String wireName = r'$ChatCompletionResponseMessage';

  @override
  Object serialize(
    Serializers serializers,
    $ChatCompletionResponseMessage object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return serializers.serialize(object, specifiedType: FullType(ChatCompletionResponseMessage))!;
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required ChatCompletionResponseMessageBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'content':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.content = valueDes;
          break;
        case r'refusal':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.refusal = valueDes;
          break;
        case r'tool_calls':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(BuiltList, [FullType(ChatCompletionMessageToolCall)]),
          ) as BuiltList<ChatCompletionMessageToolCall>;
          result.toolCalls.replace(valueDes);
          break;
        case r'annotations':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(BuiltList, [FullType(ChatCompletionResponseMessageAnnotationsInner)]),
          ) as BuiltList<ChatCompletionResponseMessageAnnotationsInner>;
          result.annotations.replace(valueDes);
          break;
        case r'role':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(ChatCompletionResponseMessageRoleEnum),
          ) as ChatCompletionResponseMessageRoleEnum;
          result.role = valueDes;
          break;
        case r'function_call':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(ChatCompletionResponseMessageFunctionCall),
          ) as ChatCompletionResponseMessageFunctionCall;
          result.functionCall.replace(valueDes);
          break;
        case r'audio':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(ChatCompletionResponseMessageAudio),
          ) as ChatCompletionResponseMessageAudio;
          result.audio.replace(valueDes);
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  $ChatCompletionResponseMessage deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = $ChatCompletionResponseMessageBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class ChatCompletionResponseMessageRoleEnum extends EnumClass {

  /// The role of the author of this message.
  @BuiltValueEnumConst(wireName: r'assistant')
  static const ChatCompletionResponseMessageRoleEnum assistant = _$chatCompletionResponseMessageRoleEnum_assistant;

  static Serializer<ChatCompletionResponseMessageRoleEnum> get serializer => _$chatCompletionResponseMessageRoleEnumSerializer;

  const ChatCompletionResponseMessageRoleEnum._(String name): super(name);

  static BuiltSet<ChatCompletionResponseMessageRoleEnum> get values => _$chatCompletionResponseMessageRoleEnumValues;
  static ChatCompletionResponseMessageRoleEnum valueOf(String name) => _$chatCompletionResponseMessageRoleEnumValueOf(name);
}

