//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:openai_flutter_sdk/src/model/easy_input_message_content.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'easy_input_message.g.dart';

/// A message input to the model with a role indicating instruction following hierarchy. Instructions given with the `developer` or `system` role take precedence over instructions given with the `user` role. Messages with the `assistant` role are presumed to have been generated by the model in previous interactions. 
///
/// Properties:
/// * [role] - The role of the message input. One of `user`, `assistant`, `system`, or `developer`. 
/// * [content] 
/// * [type] - The type of the message input. Always `message`. 
@BuiltValue()
abstract class EasyInputMessage implements Built<EasyInputMessage, EasyInputMessageBuilder> {
  /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`. 
  @BuiltValueField(wireName: r'role')
  EasyInputMessageRoleEnum get role;
  // enum roleEnum {  user,  assistant,  system,  developer,  };

  @BuiltValueField(wireName: r'content')
  EasyInputMessageContent get content;

  /// The type of the message input. Always `message`. 
  @BuiltValueField(wireName: r'type')
  EasyInputMessageTypeEnum? get type;
  // enum typeEnum {  message,  };

  EasyInputMessage._();

  factory EasyInputMessage([void updates(EasyInputMessageBuilder b)]) = _$EasyInputMessage;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(EasyInputMessageBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<EasyInputMessage> get serializer => _$EasyInputMessageSerializer();
}

class _$EasyInputMessageSerializer implements PrimitiveSerializer<EasyInputMessage> {
  @override
  final Iterable<Type> types = const [EasyInputMessage, _$EasyInputMessage];

  @override
  final String wireName = r'EasyInputMessage';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    EasyInputMessage object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'role';
    yield serializers.serialize(
      object.role,
      specifiedType: const FullType(EasyInputMessageRoleEnum),
    );
    yield r'content';
    yield serializers.serialize(
      object.content,
      specifiedType: const FullType(EasyInputMessageContent),
    );
    if (object.type != null) {
      yield r'type';
      yield serializers.serialize(
        object.type,
        specifiedType: const FullType(EasyInputMessageTypeEnum),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    EasyInputMessage object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required EasyInputMessageBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'role':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(EasyInputMessageRoleEnum),
          ) as EasyInputMessageRoleEnum;
          result.role = valueDes;
          break;
        case r'content':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(EasyInputMessageContent),
          ) as EasyInputMessageContent;
          result.content.replace(valueDes);
          break;
        case r'type':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(EasyInputMessageTypeEnum),
          ) as EasyInputMessageTypeEnum;
          result.type = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  EasyInputMessage deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = EasyInputMessageBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class EasyInputMessageRoleEnum extends EnumClass {

  /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`. 
  @BuiltValueEnumConst(wireName: r'user')
  static const EasyInputMessageRoleEnum user = _$easyInputMessageRoleEnum_user;
  /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`. 
  @BuiltValueEnumConst(wireName: r'assistant')
  static const EasyInputMessageRoleEnum assistant = _$easyInputMessageRoleEnum_assistant;
  /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`. 
  @BuiltValueEnumConst(wireName: r'system')
  static const EasyInputMessageRoleEnum system = _$easyInputMessageRoleEnum_system;
  /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`. 
  @BuiltValueEnumConst(wireName: r'developer')
  static const EasyInputMessageRoleEnum developer = _$easyInputMessageRoleEnum_developer;

  static Serializer<EasyInputMessageRoleEnum> get serializer => _$easyInputMessageRoleEnumSerializer;

  const EasyInputMessageRoleEnum._(String name): super(name);

  static BuiltSet<EasyInputMessageRoleEnum> get values => _$easyInputMessageRoleEnumValues;
  static EasyInputMessageRoleEnum valueOf(String name) => _$easyInputMessageRoleEnumValueOf(name);
}

class EasyInputMessageTypeEnum extends EnumClass {

  /// The type of the message input. Always `message`. 
  @BuiltValueEnumConst(wireName: r'message')
  static const EasyInputMessageTypeEnum message = _$easyInputMessageTypeEnum_message;

  static Serializer<EasyInputMessageTypeEnum> get serializer => _$easyInputMessageTypeEnumSerializer;

  const EasyInputMessageTypeEnum._(String name): super(name);

  static BuiltSet<EasyInputMessageTypeEnum> get values => _$easyInputMessageTypeEnumValues;
  static EasyInputMessageTypeEnum valueOf(String name) => _$easyInputMessageTypeEnumValueOf(name);
}

