//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_request_assistant_message_function_call.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_request_user_message.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_request_tool_message.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_request_tool_message_content.dart';
import 'package:openai_flutter_sdk/src/model/fine_tune_chat_completion_request_assistant_message.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_request_assistant_message_audio.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_request_developer_message.dart';
import 'package:openai_flutter_sdk/src/model/chat_completion_message_tool_call.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:one_of/one_of.dart';

part 'fine_tune_reinforcement_request_input_messages_inner.g.dart';

/// FineTuneReinforcementRequestInputMessagesInner
///
/// Properties:
/// * [content] 
/// * [role] - The role of the messages author, in this case `tool`.
/// * [name] - An optional name for the participant. Provides the model information to differentiate between participants of the same role.
/// * [weight] - Controls whether the assistant message is trained against (0 or 1)
/// * [refusal] - The refusal message by the assistant.
/// * [audio] 
/// * [toolCalls] - The tool calls generated by the model, such as function calls.
/// * [functionCall] 
/// * [toolCallId] - Tool call that this message is responding to.
@BuiltValue()
abstract class FineTuneReinforcementRequestInputMessagesInner implements Built<FineTuneReinforcementRequestInputMessagesInner, FineTuneReinforcementRequestInputMessagesInnerBuilder> {
  /// One Of [ChatCompletionRequestDeveloperMessage], [ChatCompletionRequestToolMessage], [ChatCompletionRequestUserMessage], [FineTuneChatCompletionRequestAssistantMessage]
  OneOf get oneOf;

  FineTuneReinforcementRequestInputMessagesInner._();

  factory FineTuneReinforcementRequestInputMessagesInner([void updates(FineTuneReinforcementRequestInputMessagesInnerBuilder b)]) = _$FineTuneReinforcementRequestInputMessagesInner;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(FineTuneReinforcementRequestInputMessagesInnerBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<FineTuneReinforcementRequestInputMessagesInner> get serializer => _$FineTuneReinforcementRequestInputMessagesInnerSerializer();
}

class _$FineTuneReinforcementRequestInputMessagesInnerSerializer implements PrimitiveSerializer<FineTuneReinforcementRequestInputMessagesInner> {
  @override
  final Iterable<Type> types = const [FineTuneReinforcementRequestInputMessagesInner, _$FineTuneReinforcementRequestInputMessagesInner];

  @override
  final String wireName = r'FineTuneReinforcementRequestInputMessagesInner';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    FineTuneReinforcementRequestInputMessagesInner object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
  }

  @override
  Object serialize(
    Serializers serializers,
    FineTuneReinforcementRequestInputMessagesInner object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final oneOf = object.oneOf;
    return serializers.serialize(oneOf.value, specifiedType: FullType(oneOf.valueType))!;
  }

  @override
  FineTuneReinforcementRequestInputMessagesInner deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = FineTuneReinforcementRequestInputMessagesInnerBuilder();
    Object? oneOfDataSrc;
    final targetType = const FullType(OneOf, [FullType(ChatCompletionRequestDeveloperMessage), FullType(ChatCompletionRequestUserMessage), FullType(FineTuneChatCompletionRequestAssistantMessage), FullType(ChatCompletionRequestToolMessage), ]);
    oneOfDataSrc = serialized;
    result.oneOf = serializers.deserialize(oneOfDataSrc, specifiedType: targetType) as OneOf;
    return result.build();
  }
}

class FineTuneReinforcementRequestInputMessagesInnerRoleEnum extends EnumClass {

  /// The role of the messages author, in this case `tool`.
  @BuiltValueEnumConst(wireName: r'tool')
  static const FineTuneReinforcementRequestInputMessagesInnerRoleEnum tool = _$fineTuneReinforcementRequestInputMessagesInnerRoleEnum_tool;

  static Serializer<FineTuneReinforcementRequestInputMessagesInnerRoleEnum> get serializer => _$fineTuneReinforcementRequestInputMessagesInnerRoleEnumSerializer;

  const FineTuneReinforcementRequestInputMessagesInnerRoleEnum._(String name): super(name);

  static BuiltSet<FineTuneReinforcementRequestInputMessagesInnerRoleEnum> get values => _$fineTuneReinforcementRequestInputMessagesInnerRoleEnumValues;
  static FineTuneReinforcementRequestInputMessagesInnerRoleEnum valueOf(String name) => _$fineTuneReinforcementRequestInputMessagesInnerRoleEnumValueOf(name);
}

class FineTuneReinforcementRequestInputMessagesInnerWeightEnum extends EnumClass {

  /// Controls whether the assistant message is trained against (0 or 1)
  @BuiltValueEnumConst(wireNumber: 0)
  static const FineTuneReinforcementRequestInputMessagesInnerWeightEnum number0 = _$fineTuneReinforcementRequestInputMessagesInnerWeightEnum_number0;
  /// Controls whether the assistant message is trained against (0 or 1)
  @BuiltValueEnumConst(wireNumber: 1)
  static const FineTuneReinforcementRequestInputMessagesInnerWeightEnum number1 = _$fineTuneReinforcementRequestInputMessagesInnerWeightEnum_number1;

  static Serializer<FineTuneReinforcementRequestInputMessagesInnerWeightEnum> get serializer => _$fineTuneReinforcementRequestInputMessagesInnerWeightEnumSerializer;

  const FineTuneReinforcementRequestInputMessagesInnerWeightEnum._(String name): super(name);

  static BuiltSet<FineTuneReinforcementRequestInputMessagesInnerWeightEnum> get values => _$fineTuneReinforcementRequestInputMessagesInnerWeightEnumValues;
  static FineTuneReinforcementRequestInputMessagesInnerWeightEnum valueOf(String name) => _$fineTuneReinforcementRequestInputMessagesInnerWeightEnumValueOf(name);
}

