//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'function_tool_call_output.g.dart';

/// The output of a function tool call. 
///
/// Properties:
/// * [id] - The unique ID of the function tool call output. Populated when this item is returned via API. 
/// * [type] - The type of the function tool call output. Always `function_call_output`. 
/// * [callId] - The unique ID of the function tool call generated by the model. 
/// * [output] - A JSON string of the output of the function tool call. 
/// * [status] - The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
@BuiltValue(instantiable: false)
abstract class FunctionToolCallOutput  {
  /// The unique ID of the function tool call output. Populated when this item is returned via API. 
  @BuiltValueField(wireName: r'id')
  String? get id;

  /// The type of the function tool call output. Always `function_call_output`. 
  @BuiltValueField(wireName: r'type')
  FunctionToolCallOutputTypeEnum get type;
  // enum typeEnum {  function_call_output,  };

  /// The unique ID of the function tool call generated by the model. 
  @BuiltValueField(wireName: r'call_id')
  String get callId;

  /// A JSON string of the output of the function tool call. 
  @BuiltValueField(wireName: r'output')
  String get output;

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
  @BuiltValueField(wireName: r'status')
  FunctionToolCallOutputStatusEnum? get status;
  // enum statusEnum {  in_progress,  completed,  incomplete,  };

  @BuiltValueSerializer(custom: true)
  static Serializer<FunctionToolCallOutput> get serializer => _$FunctionToolCallOutputSerializer();
}

class _$FunctionToolCallOutputSerializer implements PrimitiveSerializer<FunctionToolCallOutput> {
  @override
  final Iterable<Type> types = const [FunctionToolCallOutput];

  @override
  final String wireName = r'FunctionToolCallOutput';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    FunctionToolCallOutput object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    if (object.id != null) {
      yield r'id';
      yield serializers.serialize(
        object.id,
        specifiedType: const FullType(String),
      );
    }
    yield r'type';
    yield serializers.serialize(
      object.type,
      specifiedType: const FullType(FunctionToolCallOutputTypeEnum),
    );
    yield r'call_id';
    yield serializers.serialize(
      object.callId,
      specifiedType: const FullType(String),
    );
    yield r'output';
    yield serializers.serialize(
      object.output,
      specifiedType: const FullType(String),
    );
    if (object.status != null) {
      yield r'status';
      yield serializers.serialize(
        object.status,
        specifiedType: const FullType(FunctionToolCallOutputStatusEnum),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    FunctionToolCallOutput object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  @override
  FunctionToolCallOutput deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return serializers.deserialize(serialized, specifiedType: FullType($FunctionToolCallOutput)) as $FunctionToolCallOutput;
  }
}

/// a concrete implementation of [FunctionToolCallOutput], since [FunctionToolCallOutput] is not instantiable
@BuiltValue(instantiable: true)
abstract class $FunctionToolCallOutput implements FunctionToolCallOutput, Built<$FunctionToolCallOutput, $FunctionToolCallOutputBuilder> {
  $FunctionToolCallOutput._();

  factory $FunctionToolCallOutput([void Function($FunctionToolCallOutputBuilder)? updates]) = _$$FunctionToolCallOutput;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults($FunctionToolCallOutputBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<$FunctionToolCallOutput> get serializer => _$$FunctionToolCallOutputSerializer();
}

class _$$FunctionToolCallOutputSerializer implements PrimitiveSerializer<$FunctionToolCallOutput> {
  @override
  final Iterable<Type> types = const [$FunctionToolCallOutput, _$$FunctionToolCallOutput];

  @override
  final String wireName = r'$FunctionToolCallOutput';

  @override
  Object serialize(
    Serializers serializers,
    $FunctionToolCallOutput object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return serializers.serialize(object, specifiedType: FullType(FunctionToolCallOutput))!;
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required FunctionToolCallOutputBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.id = valueDes;
          break;
        case r'type':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(FunctionToolCallOutputTypeEnum),
          ) as FunctionToolCallOutputTypeEnum;
          result.type = valueDes;
          break;
        case r'call_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.callId = valueDes;
          break;
        case r'output':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.output = valueDes;
          break;
        case r'status':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(FunctionToolCallOutputStatusEnum),
          ) as FunctionToolCallOutputStatusEnum;
          result.status = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  $FunctionToolCallOutput deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = $FunctionToolCallOutputBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class FunctionToolCallOutputTypeEnum extends EnumClass {

  /// The type of the function tool call output. Always `function_call_output`. 
  @BuiltValueEnumConst(wireName: r'function_call_output')
  static const FunctionToolCallOutputTypeEnum functionCallOutput = _$functionToolCallOutputTypeEnum_functionCallOutput;

  static Serializer<FunctionToolCallOutputTypeEnum> get serializer => _$functionToolCallOutputTypeEnumSerializer;

  const FunctionToolCallOutputTypeEnum._(String name): super(name);

  static BuiltSet<FunctionToolCallOutputTypeEnum> get values => _$functionToolCallOutputTypeEnumValues;
  static FunctionToolCallOutputTypeEnum valueOf(String name) => _$functionToolCallOutputTypeEnumValueOf(name);
}

class FunctionToolCallOutputStatusEnum extends EnumClass {

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
  @BuiltValueEnumConst(wireName: r'in_progress')
  static const FunctionToolCallOutputStatusEnum inProgress = _$functionToolCallOutputStatusEnum_inProgress;
  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
  @BuiltValueEnumConst(wireName: r'completed')
  static const FunctionToolCallOutputStatusEnum completed = _$functionToolCallOutputStatusEnum_completed;
  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
  @BuiltValueEnumConst(wireName: r'incomplete')
  static const FunctionToolCallOutputStatusEnum incomplete = _$functionToolCallOutputStatusEnum_incomplete;

  static Serializer<FunctionToolCallOutputStatusEnum> get serializer => _$functionToolCallOutputStatusEnumSerializer;

  const FunctionToolCallOutputStatusEnum._(String name): super(name);

  static BuiltSet<FunctionToolCallOutputStatusEnum> get values => _$functionToolCallOutputStatusEnumValues;
  static FunctionToolCallOutputStatusEnum valueOf(String name) => _$functionToolCallOutputStatusEnumValueOf(name);
}

