//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'function_call_output_item_param.g.dart';

/// The output of a function tool call.
///
/// Properties:
/// * [id] - The unique ID of the function tool call output. Populated when this item is returned via API.
/// * [callId] - The unique ID of the function tool call generated by the model.
/// * [type] - The type of the function tool call output. Always `function_call_output`.
/// * [output] - A JSON string of the output of the function tool call.
/// * [status] - The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
@BuiltValue()
abstract class FunctionCallOutputItemParam implements Built<FunctionCallOutputItemParam, FunctionCallOutputItemParamBuilder> {
  /// The unique ID of the function tool call output. Populated when this item is returned via API.
  @BuiltValueField(wireName: r'id')
  String? get id;

  /// The unique ID of the function tool call generated by the model.
  @BuiltValueField(wireName: r'call_id')
  String get callId;

  /// The type of the function tool call output. Always `function_call_output`.
  @BuiltValueField(wireName: r'type')
  FunctionCallOutputItemParamTypeEnum get type;
  // enum typeEnum {  function_call_output,  };

  /// A JSON string of the output of the function tool call.
  @BuiltValueField(wireName: r'output')
  String get output;

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  @BuiltValueField(wireName: r'status')
  FunctionCallOutputItemParamStatusEnum? get status;
  // enum statusEnum {  in_progress,  completed,  incomplete,  };

  FunctionCallOutputItemParam._();

  factory FunctionCallOutputItemParam([void updates(FunctionCallOutputItemParamBuilder b)]) = _$FunctionCallOutputItemParam;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(FunctionCallOutputItemParamBuilder b) => b
      ..type = const FunctionCallOutputItemParamTypeEnum._('function_call_output');

  @BuiltValueSerializer(custom: true)
  static Serializer<FunctionCallOutputItemParam> get serializer => _$FunctionCallOutputItemParamSerializer();
}

class _$FunctionCallOutputItemParamSerializer implements PrimitiveSerializer<FunctionCallOutputItemParam> {
  @override
  final Iterable<Type> types = const [FunctionCallOutputItemParam, _$FunctionCallOutputItemParam];

  @override
  final String wireName = r'FunctionCallOutputItemParam';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    FunctionCallOutputItemParam object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    if (object.id != null) {
      yield r'id';
      yield serializers.serialize(
        object.id,
        specifiedType: const FullType.nullable(String),
      );
    }
    yield r'call_id';
    yield serializers.serialize(
      object.callId,
      specifiedType: const FullType(String),
    );
    yield r'type';
    yield serializers.serialize(
      object.type,
      specifiedType: const FullType(FunctionCallOutputItemParamTypeEnum),
    );
    yield r'output';
    yield serializers.serialize(
      object.output,
      specifiedType: const FullType(String),
    );
    if (object.status != null) {
      yield r'status';
      yield serializers.serialize(
        object.status,
        specifiedType: const FullType.nullable(FunctionCallOutputItemParamStatusEnum),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    FunctionCallOutputItemParam object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required FunctionCallOutputItemParamBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.id = valueDes;
          break;
        case r'call_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.callId = valueDes;
          break;
        case r'type':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(FunctionCallOutputItemParamTypeEnum),
          ) as FunctionCallOutputItemParamTypeEnum;
          result.type = valueDes;
          break;
        case r'output':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.output = valueDes;
          break;
        case r'status':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(FunctionCallOutputItemParamStatusEnum),
          ) as FunctionCallOutputItemParamStatusEnum?;
          if (valueDes == null) continue;
          result.status = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  FunctionCallOutputItemParam deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = FunctionCallOutputItemParamBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class FunctionCallOutputItemParamTypeEnum extends EnumClass {

  /// The type of the function tool call output. Always `function_call_output`.
  @BuiltValueEnumConst(wireName: r'function_call_output')
  static const FunctionCallOutputItemParamTypeEnum functionCallOutput = _$functionCallOutputItemParamTypeEnum_functionCallOutput;

  static Serializer<FunctionCallOutputItemParamTypeEnum> get serializer => _$functionCallOutputItemParamTypeEnumSerializer;

  const FunctionCallOutputItemParamTypeEnum._(String name): super(name);

  static BuiltSet<FunctionCallOutputItemParamTypeEnum> get values => _$functionCallOutputItemParamTypeEnumValues;
  static FunctionCallOutputItemParamTypeEnum valueOf(String name) => _$functionCallOutputItemParamTypeEnumValueOf(name);
}

class FunctionCallOutputItemParamStatusEnum extends EnumClass {

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  @BuiltValueEnumConst(wireName: r'in_progress')
  static const FunctionCallOutputItemParamStatusEnum inProgress = _$functionCallOutputItemParamStatusEnum_inProgress;
  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  @BuiltValueEnumConst(wireName: r'completed')
  static const FunctionCallOutputItemParamStatusEnum completed = _$functionCallOutputItemParamStatusEnum_completed;
  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  @BuiltValueEnumConst(wireName: r'incomplete')
  static const FunctionCallOutputItemParamStatusEnum incomplete = _$functionCallOutputItemParamStatusEnum_incomplete;

  static Serializer<FunctionCallOutputItemParamStatusEnum> get serializer => _$functionCallOutputItemParamStatusEnumSerializer;

  const FunctionCallOutputItemParamStatusEnum._(String name): super(name);

  static BuiltSet<FunctionCallOutputItemParamStatusEnum> get values => _$functionCallOutputItemParamStatusEnumValues;
  static FunctionCallOutputItemParamStatusEnum valueOf(String name) => _$functionCallOutputItemParamStatusEnumValueOf(name);
}

