//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class ChatCompletionMessageListDataInner {
  /// Returns a new [ChatCompletionMessageListDataInner] instance.
  ChatCompletionMessageListDataInner({
    required this.content,
    required this.refusal,
    this.toolCalls = const [],
    this.annotations = const [],
    required this.role,
    this.functionCall,
    this.audio,
    required this.id,
  });

  /// The contents of the message.
  String content;

  /// The refusal message generated by the model.
  String refusal;

  /// The tool calls generated by the model, such as function calls.
  List<ChatCompletionMessageToolCall> toolCalls;

  /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
  List<ChatCompletionResponseMessageAnnotationsInner> annotations;

  /// The role of the author of this message.
  ChatCompletionMessageListDataInnerRoleEnum role;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  ChatCompletionResponseMessageFunctionCall? functionCall;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  ChatCompletionResponseMessageAudio? audio;

  /// The identifier of the chat message.
  String id;

  @override
  bool operator ==(Object other) => identical(this, other) || other is ChatCompletionMessageListDataInner &&
    other.content == content &&
    other.refusal == refusal &&
    _deepEquality.equals(other.toolCalls, toolCalls) &&
    _deepEquality.equals(other.annotations, annotations) &&
    other.role == role &&
    other.functionCall == functionCall &&
    other.audio == audio &&
    other.id == id;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (content.hashCode) +
    (refusal.hashCode) +
    (toolCalls.hashCode) +
    (annotations.hashCode) +
    (role.hashCode) +
    (functionCall == null ? 0 : functionCall!.hashCode) +
    (audio == null ? 0 : audio!.hashCode) +
    (id.hashCode);

  @override
  String toString() => 'ChatCompletionMessageListDataInner[content=$content, refusal=$refusal, toolCalls=$toolCalls, annotations=$annotations, role=$role, functionCall=$functionCall, audio=$audio, id=$id]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'content'] = this.content;
      json[r'refusal'] = this.refusal;
      json[r'tool_calls'] = this.toolCalls;
      json[r'annotations'] = this.annotations;
      json[r'role'] = this.role;
    if (this.functionCall != null) {
      json[r'function_call'] = this.functionCall;
    } else {
      json[r'function_call'] = null;
    }
    if (this.audio != null) {
      json[r'audio'] = this.audio;
    } else {
      json[r'audio'] = null;
    }
      json[r'id'] = this.id;
    return json;
  }

  /// Returns a new [ChatCompletionMessageListDataInner] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static ChatCompletionMessageListDataInner? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "ChatCompletionMessageListDataInner[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "ChatCompletionMessageListDataInner[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return ChatCompletionMessageListDataInner(
        content: mapValueOfType<String>(json, r'content')!,
        refusal: mapValueOfType<String>(json, r'refusal')!,
        toolCalls: ChatCompletionMessageToolCall.listFromJson(json[r'tool_calls']),
        annotations: ChatCompletionResponseMessageAnnotationsInner.listFromJson(json[r'annotations']),
        role: ChatCompletionMessageListDataInnerRoleEnum.fromJson(json[r'role'])!,
        functionCall: ChatCompletionResponseMessageFunctionCall.fromJson(json[r'function_call']),
        audio: ChatCompletionResponseMessageAudio.fromJson(json[r'audio']),
        id: mapValueOfType<String>(json, r'id')!,
      );
    }
    return null;
  }

  static List<ChatCompletionMessageListDataInner> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <ChatCompletionMessageListDataInner>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = ChatCompletionMessageListDataInner.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, ChatCompletionMessageListDataInner> mapFromJson(dynamic json) {
    final map = <String, ChatCompletionMessageListDataInner>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = ChatCompletionMessageListDataInner.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of ChatCompletionMessageListDataInner-objects as value to a dart map
  static Map<String, List<ChatCompletionMessageListDataInner>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<ChatCompletionMessageListDataInner>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = ChatCompletionMessageListDataInner.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'content',
    'refusal',
    'role',
    'id',
  };
}

/// The role of the author of this message.
class ChatCompletionMessageListDataInnerRoleEnum {
  /// Instantiate a new enum with the provided [value].
  const ChatCompletionMessageListDataInnerRoleEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const assistant = ChatCompletionMessageListDataInnerRoleEnum._(r'assistant');

  /// List of all possible values in this [enum][ChatCompletionMessageListDataInnerRoleEnum].
  static const values = <ChatCompletionMessageListDataInnerRoleEnum>[
    assistant,
  ];

  static ChatCompletionMessageListDataInnerRoleEnum? fromJson(dynamic value) => ChatCompletionMessageListDataInnerRoleEnumTypeTransformer().decode(value);

  static List<ChatCompletionMessageListDataInnerRoleEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <ChatCompletionMessageListDataInnerRoleEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = ChatCompletionMessageListDataInnerRoleEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [ChatCompletionMessageListDataInnerRoleEnum] to String,
/// and [decode] dynamic data back to [ChatCompletionMessageListDataInnerRoleEnum].
class ChatCompletionMessageListDataInnerRoleEnumTypeTransformer {
  factory ChatCompletionMessageListDataInnerRoleEnumTypeTransformer() => _instance ??= const ChatCompletionMessageListDataInnerRoleEnumTypeTransformer._();

  const ChatCompletionMessageListDataInnerRoleEnumTypeTransformer._();

  String encode(ChatCompletionMessageListDataInnerRoleEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a ChatCompletionMessageListDataInnerRoleEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  ChatCompletionMessageListDataInnerRoleEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'assistant': return ChatCompletionMessageListDataInnerRoleEnum.assistant;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [ChatCompletionMessageListDataInnerRoleEnumTypeTransformer] instance.
  static ChatCompletionMessageListDataInnerRoleEnumTypeTransformer? _instance;
}


