//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class CompletionUsageCompletionTokensDetails {
  /// Returns a new [CompletionUsageCompletionTokensDetails] instance.
  CompletionUsageCompletionTokensDetails({
    this.acceptedPredictionTokens = 0,
    this.audioTokens = 0,
    this.reasoningTokens = 0,
    this.rejectedPredictionTokens = 0,
  });

  /// When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion. 
  int acceptedPredictionTokens;

  /// Audio input tokens generated by the model.
  int audioTokens;

  /// Tokens generated by the model for reasoning.
  int reasoningTokens;

  /// When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits. 
  int rejectedPredictionTokens;

  @override
  bool operator ==(Object other) => identical(this, other) || other is CompletionUsageCompletionTokensDetails &&
    other.acceptedPredictionTokens == acceptedPredictionTokens &&
    other.audioTokens == audioTokens &&
    other.reasoningTokens == reasoningTokens &&
    other.rejectedPredictionTokens == rejectedPredictionTokens;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (acceptedPredictionTokens.hashCode) +
    (audioTokens.hashCode) +
    (reasoningTokens.hashCode) +
    (rejectedPredictionTokens.hashCode);

  @override
  String toString() => 'CompletionUsageCompletionTokensDetails[acceptedPredictionTokens=$acceptedPredictionTokens, audioTokens=$audioTokens, reasoningTokens=$reasoningTokens, rejectedPredictionTokens=$rejectedPredictionTokens]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'accepted_prediction_tokens'] = this.acceptedPredictionTokens;
      json[r'audio_tokens'] = this.audioTokens;
      json[r'reasoning_tokens'] = this.reasoningTokens;
      json[r'rejected_prediction_tokens'] = this.rejectedPredictionTokens;
    return json;
  }

  /// Returns a new [CompletionUsageCompletionTokensDetails] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static CompletionUsageCompletionTokensDetails? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "CompletionUsageCompletionTokensDetails[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "CompletionUsageCompletionTokensDetails[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return CompletionUsageCompletionTokensDetails(
        acceptedPredictionTokens: mapValueOfType<int>(json, r'accepted_prediction_tokens') ?? 0,
        audioTokens: mapValueOfType<int>(json, r'audio_tokens') ?? 0,
        reasoningTokens: mapValueOfType<int>(json, r'reasoning_tokens') ?? 0,
        rejectedPredictionTokens: mapValueOfType<int>(json, r'rejected_prediction_tokens') ?? 0,
      );
    }
    return null;
  }

  static List<CompletionUsageCompletionTokensDetails> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CompletionUsageCompletionTokensDetails>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CompletionUsageCompletionTokensDetails.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, CompletionUsageCompletionTokensDetails> mapFromJson(dynamic json) {
    final map = <String, CompletionUsageCompletionTokensDetails>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = CompletionUsageCompletionTokensDetails.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of CompletionUsageCompletionTokensDetails-objects as value to a dart map
  static Map<String, List<CompletionUsageCompletionTokensDetails>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<CompletionUsageCompletionTokensDetails>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = CompletionUsageCompletionTokensDetails.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
  };
}

