//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class CreateImageRequest {
  /// Returns a new [CreateImageRequest] instance.
  CreateImageRequest({
    required this.prompt,
    this.model,
    this.n = 1,
    this.quality = const CreateImageRequestQualityEnum._('auto'),
    this.responseFormat = const CreateImageRequestResponseFormatEnum._('url'),
    this.outputFormat = const CreateImageRequestOutputFormatEnum._('png'),
    this.outputCompression = 100,
    this.size = const CreateImageRequestSizeEnum._('auto'),
    this.moderation = const CreateImageRequestModerationEnum._('auto'),
    this.background = const CreateImageRequestBackgroundEnum._('auto'),
    this.style = const CreateImageRequestStyleEnum._('vivid'),
    this.user,
  });

  /// A text description of the desired image(s). The maximum length is 32000 characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
  String prompt;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  CreateImageRequestModel? model;

  /// The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.
  ///
  /// Minimum value: 1
  /// Maximum value: 10
  int n;

  /// The quality of the image that will be generated.   - `auto` (default value) will automatically select the best quality for the given model. - `high`, `medium` and `low` are supported for `gpt-image-1`. - `hd` and `standard` are supported for `dall-e-3`. - `standard` is the only option for `dall-e-2`. 
  CreateImageRequestQualityEnum quality;

  /// The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for `gpt-image-1` which will always return base64-encoded images.
  CreateImageRequestResponseFormatEnum responseFormat;

  /// The format in which the generated images are returned. This parameter is only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
  CreateImageRequestOutputFormatEnum outputFormat;

  /// The compression level (0-100%) for the generated images. This parameter is only supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and defaults to 100.
  int outputCompression;

  /// The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
  CreateImageRequestSizeEnum size;

  /// Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).
  CreateImageRequestModerationEnum moderation;

  /// Allows to set transparency for the background of the generated image(s).  This parameter is only supported for `gpt-image-1`. Must be one of  `transparent`, `opaque` or `auto` (default value). When `auto` is used, the  model will automatically determine the best background for the image.  If `transparent`, the output format needs to support transparency, so it  should be set to either `png` (default value) or `webp`. 
  CreateImageRequestBackgroundEnum background;

  /// The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.
  CreateImageRequestStyleEnum style;

  /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids). 
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? user;

  @override
  bool operator ==(Object other) => identical(this, other) || other is CreateImageRequest &&
    other.prompt == prompt &&
    other.model == model &&
    other.n == n &&
    other.quality == quality &&
    other.responseFormat == responseFormat &&
    other.outputFormat == outputFormat &&
    other.outputCompression == outputCompression &&
    other.size == size &&
    other.moderation == moderation &&
    other.background == background &&
    other.style == style &&
    other.user == user;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (prompt.hashCode) +
    (model == null ? 0 : model!.hashCode) +
    (n.hashCode) +
    (quality.hashCode) +
    (responseFormat.hashCode) +
    (outputFormat.hashCode) +
    (outputCompression.hashCode) +
    (size.hashCode) +
    (moderation.hashCode) +
    (background.hashCode) +
    (style.hashCode) +
    (user == null ? 0 : user!.hashCode);

  @override
  String toString() => 'CreateImageRequest[prompt=$prompt, model=$model, n=$n, quality=$quality, responseFormat=$responseFormat, outputFormat=$outputFormat, outputCompression=$outputCompression, size=$size, moderation=$moderation, background=$background, style=$style, user=$user]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'prompt'] = this.prompt;
    if (this.model != null) {
      json[r'model'] = this.model;
    } else {
      json[r'model'] = null;
    }
      json[r'n'] = this.n;
      json[r'quality'] = this.quality;
      json[r'response_format'] = this.responseFormat;
      json[r'output_format'] = this.outputFormat;
      json[r'output_compression'] = this.outputCompression;
      json[r'size'] = this.size;
      json[r'moderation'] = this.moderation;
      json[r'background'] = this.background;
      json[r'style'] = this.style;
    if (this.user != null) {
      json[r'user'] = this.user;
    } else {
      json[r'user'] = null;
    }
    return json;
  }

  /// Returns a new [CreateImageRequest] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static CreateImageRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "CreateImageRequest[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "CreateImageRequest[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return CreateImageRequest(
        prompt: mapValueOfType<String>(json, r'prompt')!,
        model: CreateImageRequestModel.fromJson(json[r'model']),
        n: mapValueOfType<int>(json, r'n') ?? 1,
        quality: CreateImageRequestQualityEnum.fromJson(json[r'quality']) ?? 'auto',
        responseFormat: CreateImageRequestResponseFormatEnum.fromJson(json[r'response_format']) ?? 'url',
        outputFormat: CreateImageRequestOutputFormatEnum.fromJson(json[r'output_format']) ?? 'png',
        outputCompression: mapValueOfType<int>(json, r'output_compression') ?? 100,
        size: CreateImageRequestSizeEnum.fromJson(json[r'size']) ?? 'auto',
        moderation: CreateImageRequestModerationEnum.fromJson(json[r'moderation']) ?? 'auto',
        background: CreateImageRequestBackgroundEnum.fromJson(json[r'background']) ?? 'auto',
        style: CreateImageRequestStyleEnum.fromJson(json[r'style']) ?? 'vivid',
        user: mapValueOfType<String>(json, r'user'),
      );
    }
    return null;
  }

  static List<CreateImageRequest> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, CreateImageRequest> mapFromJson(dynamic json) {
    final map = <String, CreateImageRequest>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = CreateImageRequest.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of CreateImageRequest-objects as value to a dart map
  static Map<String, List<CreateImageRequest>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<CreateImageRequest>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = CreateImageRequest.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'prompt',
  };
}

/// The quality of the image that will be generated.   - `auto` (default value) will automatically select the best quality for the given model. - `high`, `medium` and `low` are supported for `gpt-image-1`. - `hd` and `standard` are supported for `dall-e-3`. - `standard` is the only option for `dall-e-2`. 
class CreateImageRequestQualityEnum {
  /// Instantiate a new enum with the provided [value].
  const CreateImageRequestQualityEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const standard = CreateImageRequestQualityEnum._(r'standard');
  static const hd = CreateImageRequestQualityEnum._(r'hd');
  static const low = CreateImageRequestQualityEnum._(r'low');
  static const medium = CreateImageRequestQualityEnum._(r'medium');
  static const high = CreateImageRequestQualityEnum._(r'high');
  static const auto = CreateImageRequestQualityEnum._(r'auto');

  /// List of all possible values in this [enum][CreateImageRequestQualityEnum].
  static const values = <CreateImageRequestQualityEnum>[
    standard,
    hd,
    low,
    medium,
    high,
    auto,
  ];

  static CreateImageRequestQualityEnum? fromJson(dynamic value) => CreateImageRequestQualityEnumTypeTransformer().decode(value);

  static List<CreateImageRequestQualityEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequestQualityEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequestQualityEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [CreateImageRequestQualityEnum] to String,
/// and [decode] dynamic data back to [CreateImageRequestQualityEnum].
class CreateImageRequestQualityEnumTypeTransformer {
  factory CreateImageRequestQualityEnumTypeTransformer() => _instance ??= const CreateImageRequestQualityEnumTypeTransformer._();

  const CreateImageRequestQualityEnumTypeTransformer._();

  String encode(CreateImageRequestQualityEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a CreateImageRequestQualityEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  CreateImageRequestQualityEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'standard': return CreateImageRequestQualityEnum.standard;
        case r'hd': return CreateImageRequestQualityEnum.hd;
        case r'low': return CreateImageRequestQualityEnum.low;
        case r'medium': return CreateImageRequestQualityEnum.medium;
        case r'high': return CreateImageRequestQualityEnum.high;
        case r'auto': return CreateImageRequestQualityEnum.auto;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [CreateImageRequestQualityEnumTypeTransformer] instance.
  static CreateImageRequestQualityEnumTypeTransformer? _instance;
}


/// The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for `gpt-image-1` which will always return base64-encoded images.
class CreateImageRequestResponseFormatEnum {
  /// Instantiate a new enum with the provided [value].
  const CreateImageRequestResponseFormatEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const url = CreateImageRequestResponseFormatEnum._(r'url');
  static const b64Json = CreateImageRequestResponseFormatEnum._(r'b64_json');

  /// List of all possible values in this [enum][CreateImageRequestResponseFormatEnum].
  static const values = <CreateImageRequestResponseFormatEnum>[
    url,
    b64Json,
  ];

  static CreateImageRequestResponseFormatEnum? fromJson(dynamic value) => CreateImageRequestResponseFormatEnumTypeTransformer().decode(value);

  static List<CreateImageRequestResponseFormatEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequestResponseFormatEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequestResponseFormatEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [CreateImageRequestResponseFormatEnum] to String,
/// and [decode] dynamic data back to [CreateImageRequestResponseFormatEnum].
class CreateImageRequestResponseFormatEnumTypeTransformer {
  factory CreateImageRequestResponseFormatEnumTypeTransformer() => _instance ??= const CreateImageRequestResponseFormatEnumTypeTransformer._();

  const CreateImageRequestResponseFormatEnumTypeTransformer._();

  String encode(CreateImageRequestResponseFormatEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a CreateImageRequestResponseFormatEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  CreateImageRequestResponseFormatEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'url': return CreateImageRequestResponseFormatEnum.url;
        case r'b64_json': return CreateImageRequestResponseFormatEnum.b64Json;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [CreateImageRequestResponseFormatEnumTypeTransformer] instance.
  static CreateImageRequestResponseFormatEnumTypeTransformer? _instance;
}


/// The format in which the generated images are returned. This parameter is only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
class CreateImageRequestOutputFormatEnum {
  /// Instantiate a new enum with the provided [value].
  const CreateImageRequestOutputFormatEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const png = CreateImageRequestOutputFormatEnum._(r'png');
  static const jpeg = CreateImageRequestOutputFormatEnum._(r'jpeg');
  static const webp = CreateImageRequestOutputFormatEnum._(r'webp');

  /// List of all possible values in this [enum][CreateImageRequestOutputFormatEnum].
  static const values = <CreateImageRequestOutputFormatEnum>[
    png,
    jpeg,
    webp,
  ];

  static CreateImageRequestOutputFormatEnum? fromJson(dynamic value) => CreateImageRequestOutputFormatEnumTypeTransformer().decode(value);

  static List<CreateImageRequestOutputFormatEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequestOutputFormatEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequestOutputFormatEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [CreateImageRequestOutputFormatEnum] to String,
/// and [decode] dynamic data back to [CreateImageRequestOutputFormatEnum].
class CreateImageRequestOutputFormatEnumTypeTransformer {
  factory CreateImageRequestOutputFormatEnumTypeTransformer() => _instance ??= const CreateImageRequestOutputFormatEnumTypeTransformer._();

  const CreateImageRequestOutputFormatEnumTypeTransformer._();

  String encode(CreateImageRequestOutputFormatEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a CreateImageRequestOutputFormatEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  CreateImageRequestOutputFormatEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'png': return CreateImageRequestOutputFormatEnum.png;
        case r'jpeg': return CreateImageRequestOutputFormatEnum.jpeg;
        case r'webp': return CreateImageRequestOutputFormatEnum.webp;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [CreateImageRequestOutputFormatEnumTypeTransformer] instance.
  static CreateImageRequestOutputFormatEnumTypeTransformer? _instance;
}


/// The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
class CreateImageRequestSizeEnum {
  /// Instantiate a new enum with the provided [value].
  const CreateImageRequestSizeEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const auto = CreateImageRequestSizeEnum._(r'auto');
  static const n1024x1024 = CreateImageRequestSizeEnum._(r'1024x1024');
  static const n1536x1024 = CreateImageRequestSizeEnum._(r'1536x1024');
  static const n1024x1536 = CreateImageRequestSizeEnum._(r'1024x1536');
  static const n256x256 = CreateImageRequestSizeEnum._(r'256x256');
  static const n512x512 = CreateImageRequestSizeEnum._(r'512x512');
  static const n1792x1024 = CreateImageRequestSizeEnum._(r'1792x1024');
  static const n1024x1792 = CreateImageRequestSizeEnum._(r'1024x1792');

  /// List of all possible values in this [enum][CreateImageRequestSizeEnum].
  static const values = <CreateImageRequestSizeEnum>[
    auto,
    n1024x1024,
    n1536x1024,
    n1024x1536,
    n256x256,
    n512x512,
    n1792x1024,
    n1024x1792,
  ];

  static CreateImageRequestSizeEnum? fromJson(dynamic value) => CreateImageRequestSizeEnumTypeTransformer().decode(value);

  static List<CreateImageRequestSizeEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequestSizeEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequestSizeEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [CreateImageRequestSizeEnum] to String,
/// and [decode] dynamic data back to [CreateImageRequestSizeEnum].
class CreateImageRequestSizeEnumTypeTransformer {
  factory CreateImageRequestSizeEnumTypeTransformer() => _instance ??= const CreateImageRequestSizeEnumTypeTransformer._();

  const CreateImageRequestSizeEnumTypeTransformer._();

  String encode(CreateImageRequestSizeEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a CreateImageRequestSizeEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  CreateImageRequestSizeEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'auto': return CreateImageRequestSizeEnum.auto;
        case r'1024x1024': return CreateImageRequestSizeEnum.n1024x1024;
        case r'1536x1024': return CreateImageRequestSizeEnum.n1536x1024;
        case r'1024x1536': return CreateImageRequestSizeEnum.n1024x1536;
        case r'256x256': return CreateImageRequestSizeEnum.n256x256;
        case r'512x512': return CreateImageRequestSizeEnum.n512x512;
        case r'1792x1024': return CreateImageRequestSizeEnum.n1792x1024;
        case r'1024x1792': return CreateImageRequestSizeEnum.n1024x1792;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [CreateImageRequestSizeEnumTypeTransformer] instance.
  static CreateImageRequestSizeEnumTypeTransformer? _instance;
}


/// Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).
class CreateImageRequestModerationEnum {
  /// Instantiate a new enum with the provided [value].
  const CreateImageRequestModerationEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const low = CreateImageRequestModerationEnum._(r'low');
  static const auto = CreateImageRequestModerationEnum._(r'auto');

  /// List of all possible values in this [enum][CreateImageRequestModerationEnum].
  static const values = <CreateImageRequestModerationEnum>[
    low,
    auto,
  ];

  static CreateImageRequestModerationEnum? fromJson(dynamic value) => CreateImageRequestModerationEnumTypeTransformer().decode(value);

  static List<CreateImageRequestModerationEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequestModerationEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequestModerationEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [CreateImageRequestModerationEnum] to String,
/// and [decode] dynamic data back to [CreateImageRequestModerationEnum].
class CreateImageRequestModerationEnumTypeTransformer {
  factory CreateImageRequestModerationEnumTypeTransformer() => _instance ??= const CreateImageRequestModerationEnumTypeTransformer._();

  const CreateImageRequestModerationEnumTypeTransformer._();

  String encode(CreateImageRequestModerationEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a CreateImageRequestModerationEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  CreateImageRequestModerationEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'low': return CreateImageRequestModerationEnum.low;
        case r'auto': return CreateImageRequestModerationEnum.auto;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [CreateImageRequestModerationEnumTypeTransformer] instance.
  static CreateImageRequestModerationEnumTypeTransformer? _instance;
}


/// Allows to set transparency for the background of the generated image(s).  This parameter is only supported for `gpt-image-1`. Must be one of  `transparent`, `opaque` or `auto` (default value). When `auto` is used, the  model will automatically determine the best background for the image.  If `transparent`, the output format needs to support transparency, so it  should be set to either `png` (default value) or `webp`. 
class CreateImageRequestBackgroundEnum {
  /// Instantiate a new enum with the provided [value].
  const CreateImageRequestBackgroundEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const transparent = CreateImageRequestBackgroundEnum._(r'transparent');
  static const opaque = CreateImageRequestBackgroundEnum._(r'opaque');
  static const auto = CreateImageRequestBackgroundEnum._(r'auto');

  /// List of all possible values in this [enum][CreateImageRequestBackgroundEnum].
  static const values = <CreateImageRequestBackgroundEnum>[
    transparent,
    opaque,
    auto,
  ];

  static CreateImageRequestBackgroundEnum? fromJson(dynamic value) => CreateImageRequestBackgroundEnumTypeTransformer().decode(value);

  static List<CreateImageRequestBackgroundEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequestBackgroundEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequestBackgroundEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [CreateImageRequestBackgroundEnum] to String,
/// and [decode] dynamic data back to [CreateImageRequestBackgroundEnum].
class CreateImageRequestBackgroundEnumTypeTransformer {
  factory CreateImageRequestBackgroundEnumTypeTransformer() => _instance ??= const CreateImageRequestBackgroundEnumTypeTransformer._();

  const CreateImageRequestBackgroundEnumTypeTransformer._();

  String encode(CreateImageRequestBackgroundEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a CreateImageRequestBackgroundEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  CreateImageRequestBackgroundEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'transparent': return CreateImageRequestBackgroundEnum.transparent;
        case r'opaque': return CreateImageRequestBackgroundEnum.opaque;
        case r'auto': return CreateImageRequestBackgroundEnum.auto;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [CreateImageRequestBackgroundEnumTypeTransformer] instance.
  static CreateImageRequestBackgroundEnumTypeTransformer? _instance;
}


/// The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.
class CreateImageRequestStyleEnum {
  /// Instantiate a new enum with the provided [value].
  const CreateImageRequestStyleEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const vivid = CreateImageRequestStyleEnum._(r'vivid');
  static const natural = CreateImageRequestStyleEnum._(r'natural');

  /// List of all possible values in this [enum][CreateImageRequestStyleEnum].
  static const values = <CreateImageRequestStyleEnum>[
    vivid,
    natural,
  ];

  static CreateImageRequestStyleEnum? fromJson(dynamic value) => CreateImageRequestStyleEnumTypeTransformer().decode(value);

  static List<CreateImageRequestStyleEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <CreateImageRequestStyleEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateImageRequestStyleEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [CreateImageRequestStyleEnum] to String,
/// and [decode] dynamic data back to [CreateImageRequestStyleEnum].
class CreateImageRequestStyleEnumTypeTransformer {
  factory CreateImageRequestStyleEnumTypeTransformer() => _instance ??= const CreateImageRequestStyleEnumTypeTransformer._();

  const CreateImageRequestStyleEnumTypeTransformer._();

  String encode(CreateImageRequestStyleEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a CreateImageRequestStyleEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  CreateImageRequestStyleEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'vivid': return CreateImageRequestStyleEnum.vivid;
        case r'natural': return CreateImageRequestStyleEnum.natural;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [CreateImageRequestStyleEnumTypeTransformer] instance.
  static CreateImageRequestStyleEnumTypeTransformer? _instance;
}


