//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class FineTuneReinforcementRequestInputMessagesInner {
  /// Returns a new [FineTuneReinforcementRequestInputMessagesInner] instance.
  FineTuneReinforcementRequestInputMessagesInner({
    required this.content,
    required this.role,
    this.name,
    this.weight,
    this.refusal,
    this.audio,
    this.toolCalls = const [],
    this.functionCall,
    required this.toolCallId,
  });

  ChatCompletionRequestToolMessageContent content;

  /// The role of the messages author, in this case `tool`.
  FineTuneReinforcementRequestInputMessagesInnerRoleEnum role;

  /// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? name;

  /// Controls whether the assistant message is trained against (0 or 1)
  FineTuneReinforcementRequestInputMessagesInnerWeightEnum? weight;

  /// The refusal message by the assistant.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? refusal;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  ChatCompletionRequestAssistantMessageAudio? audio;

  /// The tool calls generated by the model, such as function calls.
  List<ChatCompletionMessageToolCall> toolCalls;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  ChatCompletionRequestAssistantMessageFunctionCall? functionCall;

  /// Tool call that this message is responding to.
  String toolCallId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is FineTuneReinforcementRequestInputMessagesInner &&
    other.content == content &&
    other.role == role &&
    other.name == name &&
    other.weight == weight &&
    other.refusal == refusal &&
    other.audio == audio &&
    _deepEquality.equals(other.toolCalls, toolCalls) &&
    other.functionCall == functionCall &&
    other.toolCallId == toolCallId;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (content.hashCode) +
    (role.hashCode) +
    (name == null ? 0 : name!.hashCode) +
    (weight == null ? 0 : weight!.hashCode) +
    (refusal == null ? 0 : refusal!.hashCode) +
    (audio == null ? 0 : audio!.hashCode) +
    (toolCalls.hashCode) +
    (functionCall == null ? 0 : functionCall!.hashCode) +
    (toolCallId.hashCode);

  @override
  String toString() => 'FineTuneReinforcementRequestInputMessagesInner[content=$content, role=$role, name=$name, weight=$weight, refusal=$refusal, audio=$audio, toolCalls=$toolCalls, functionCall=$functionCall, toolCallId=$toolCallId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'content'] = this.content;
      json[r'role'] = this.role;
    if (this.name != null) {
      json[r'name'] = this.name;
    } else {
      json[r'name'] = null;
    }
    if (this.weight != null) {
      json[r'weight'] = this.weight;
    } else {
      json[r'weight'] = null;
    }
    if (this.refusal != null) {
      json[r'refusal'] = this.refusal;
    } else {
      json[r'refusal'] = null;
    }
    if (this.audio != null) {
      json[r'audio'] = this.audio;
    } else {
      json[r'audio'] = null;
    }
      json[r'tool_calls'] = this.toolCalls;
    if (this.functionCall != null) {
      json[r'function_call'] = this.functionCall;
    } else {
      json[r'function_call'] = null;
    }
      json[r'tool_call_id'] = this.toolCallId;
    return json;
  }

  /// Returns a new [FineTuneReinforcementRequestInputMessagesInner] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static FineTuneReinforcementRequestInputMessagesInner? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "FineTuneReinforcementRequestInputMessagesInner[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "FineTuneReinforcementRequestInputMessagesInner[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return FineTuneReinforcementRequestInputMessagesInner(
        content: ChatCompletionRequestToolMessageContent.fromJson(json[r'content'])!,
        role: FineTuneReinforcementRequestInputMessagesInnerRoleEnum.fromJson(json[r'role'])!,
        name: mapValueOfType<String>(json, r'name'),
        weight: FineTuneReinforcementRequestInputMessagesInnerWeightEnum.fromJson(json[r'weight']),
        refusal: mapValueOfType<String>(json, r'refusal'),
        audio: ChatCompletionRequestAssistantMessageAudio.fromJson(json[r'audio']),
        toolCalls: ChatCompletionMessageToolCall.listFromJson(json[r'tool_calls']),
        functionCall: ChatCompletionRequestAssistantMessageFunctionCall.fromJson(json[r'function_call']),
        toolCallId: mapValueOfType<String>(json, r'tool_call_id')!,
      );
    }
    return null;
  }

  static List<FineTuneReinforcementRequestInputMessagesInner> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FineTuneReinforcementRequestInputMessagesInner>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FineTuneReinforcementRequestInputMessagesInner.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, FineTuneReinforcementRequestInputMessagesInner> mapFromJson(dynamic json) {
    final map = <String, FineTuneReinforcementRequestInputMessagesInner>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = FineTuneReinforcementRequestInputMessagesInner.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of FineTuneReinforcementRequestInputMessagesInner-objects as value to a dart map
  static Map<String, List<FineTuneReinforcementRequestInputMessagesInner>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<FineTuneReinforcementRequestInputMessagesInner>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = FineTuneReinforcementRequestInputMessagesInner.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'content',
    'role',
    'tool_call_id',
  };
}

/// The role of the messages author, in this case `tool`.
class FineTuneReinforcementRequestInputMessagesInnerRoleEnum {
  /// Instantiate a new enum with the provided [value].
  const FineTuneReinforcementRequestInputMessagesInnerRoleEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const tool = FineTuneReinforcementRequestInputMessagesInnerRoleEnum._(r'tool');

  /// List of all possible values in this [enum][FineTuneReinforcementRequestInputMessagesInnerRoleEnum].
  static const values = <FineTuneReinforcementRequestInputMessagesInnerRoleEnum>[
    tool,
  ];

  static FineTuneReinforcementRequestInputMessagesInnerRoleEnum? fromJson(dynamic value) => FineTuneReinforcementRequestInputMessagesInnerRoleEnumTypeTransformer().decode(value);

  static List<FineTuneReinforcementRequestInputMessagesInnerRoleEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FineTuneReinforcementRequestInputMessagesInnerRoleEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FineTuneReinforcementRequestInputMessagesInnerRoleEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FineTuneReinforcementRequestInputMessagesInnerRoleEnum] to String,
/// and [decode] dynamic data back to [FineTuneReinforcementRequestInputMessagesInnerRoleEnum].
class FineTuneReinforcementRequestInputMessagesInnerRoleEnumTypeTransformer {
  factory FineTuneReinforcementRequestInputMessagesInnerRoleEnumTypeTransformer() => _instance ??= const FineTuneReinforcementRequestInputMessagesInnerRoleEnumTypeTransformer._();

  const FineTuneReinforcementRequestInputMessagesInnerRoleEnumTypeTransformer._();

  String encode(FineTuneReinforcementRequestInputMessagesInnerRoleEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FineTuneReinforcementRequestInputMessagesInnerRoleEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FineTuneReinforcementRequestInputMessagesInnerRoleEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'tool': return FineTuneReinforcementRequestInputMessagesInnerRoleEnum.tool;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FineTuneReinforcementRequestInputMessagesInnerRoleEnumTypeTransformer] instance.
  static FineTuneReinforcementRequestInputMessagesInnerRoleEnumTypeTransformer? _instance;
}


/// Controls whether the assistant message is trained against (0 or 1)
class FineTuneReinforcementRequestInputMessagesInnerWeightEnum {
  /// Instantiate a new enum with the provided [value].
  const FineTuneReinforcementRequestInputMessagesInnerWeightEnum._(this.value);

  /// The underlying value of this enum member.
  final int value;

  @override
  String toString() => value.toString();

  int toJson() => value;

  static const number0 = FineTuneReinforcementRequestInputMessagesInnerWeightEnum._(0);
  static const number1 = FineTuneReinforcementRequestInputMessagesInnerWeightEnum._(1);

  /// List of all possible values in this [enum][FineTuneReinforcementRequestInputMessagesInnerWeightEnum].
  static const values = <FineTuneReinforcementRequestInputMessagesInnerWeightEnum>[
    number0,
    number1,
  ];

  static FineTuneReinforcementRequestInputMessagesInnerWeightEnum? fromJson(dynamic value) => FineTuneReinforcementRequestInputMessagesInnerWeightEnumTypeTransformer().decode(value);

  static List<FineTuneReinforcementRequestInputMessagesInnerWeightEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FineTuneReinforcementRequestInputMessagesInnerWeightEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FineTuneReinforcementRequestInputMessagesInnerWeightEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FineTuneReinforcementRequestInputMessagesInnerWeightEnum] to int,
/// and [decode] dynamic data back to [FineTuneReinforcementRequestInputMessagesInnerWeightEnum].
class FineTuneReinforcementRequestInputMessagesInnerWeightEnumTypeTransformer {
  factory FineTuneReinforcementRequestInputMessagesInnerWeightEnumTypeTransformer() => _instance ??= const FineTuneReinforcementRequestInputMessagesInnerWeightEnumTypeTransformer._();

  const FineTuneReinforcementRequestInputMessagesInnerWeightEnumTypeTransformer._();

  int encode(FineTuneReinforcementRequestInputMessagesInnerWeightEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FineTuneReinforcementRequestInputMessagesInnerWeightEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FineTuneReinforcementRequestInputMessagesInnerWeightEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case 0: return FineTuneReinforcementRequestInputMessagesInnerWeightEnum.number0;
        case 1: return FineTuneReinforcementRequestInputMessagesInnerWeightEnum.number1;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FineTuneReinforcementRequestInputMessagesInnerWeightEnumTypeTransformer] instance.
  static FineTuneReinforcementRequestInputMessagesInnerWeightEnumTypeTransformer? _instance;
}


