//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class FunctionToolCallOutput {
  /// Returns a new [FunctionToolCallOutput] instance.
  FunctionToolCallOutput({
    this.id,
    required this.type,
    required this.callId,
    required this.output,
    this.status,
  });

  /// The unique ID of the function tool call output. Populated when this item is returned via API. 
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? id;

  /// The type of the function tool call output. Always `function_call_output`. 
  FunctionToolCallOutputTypeEnum type;

  /// The unique ID of the function tool call generated by the model. 
  String callId;

  /// A JSON string of the output of the function tool call. 
  String output;

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
  FunctionToolCallOutputStatusEnum? status;

  @override
  bool operator ==(Object other) => identical(this, other) || other is FunctionToolCallOutput &&
    other.id == id &&
    other.type == type &&
    other.callId == callId &&
    other.output == output &&
    other.status == status;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (id == null ? 0 : id!.hashCode) +
    (type.hashCode) +
    (callId.hashCode) +
    (output.hashCode) +
    (status == null ? 0 : status!.hashCode);

  @override
  String toString() => 'FunctionToolCallOutput[id=$id, type=$type, callId=$callId, output=$output, status=$status]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (this.id != null) {
      json[r'id'] = this.id;
    } else {
      json[r'id'] = null;
    }
      json[r'type'] = this.type;
      json[r'call_id'] = this.callId;
      json[r'output'] = this.output;
    if (this.status != null) {
      json[r'status'] = this.status;
    } else {
      json[r'status'] = null;
    }
    return json;
  }

  /// Returns a new [FunctionToolCallOutput] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static FunctionToolCallOutput? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "FunctionToolCallOutput[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "FunctionToolCallOutput[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return FunctionToolCallOutput(
        id: mapValueOfType<String>(json, r'id'),
        type: FunctionToolCallOutputTypeEnum.fromJson(json[r'type'])!,
        callId: mapValueOfType<String>(json, r'call_id')!,
        output: mapValueOfType<String>(json, r'output')!,
        status: FunctionToolCallOutputStatusEnum.fromJson(json[r'status']),
      );
    }
    return null;
  }

  static List<FunctionToolCallOutput> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionToolCallOutput>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionToolCallOutput.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, FunctionToolCallOutput> mapFromJson(dynamic json) {
    final map = <String, FunctionToolCallOutput>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = FunctionToolCallOutput.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of FunctionToolCallOutput-objects as value to a dart map
  static Map<String, List<FunctionToolCallOutput>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<FunctionToolCallOutput>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = FunctionToolCallOutput.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'type',
    'call_id',
    'output',
  };
}

/// The type of the function tool call output. Always `function_call_output`. 
class FunctionToolCallOutputTypeEnum {
  /// Instantiate a new enum with the provided [value].
  const FunctionToolCallOutputTypeEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const functionCallOutput = FunctionToolCallOutputTypeEnum._(r'function_call_output');

  /// List of all possible values in this [enum][FunctionToolCallOutputTypeEnum].
  static const values = <FunctionToolCallOutputTypeEnum>[
    functionCallOutput,
  ];

  static FunctionToolCallOutputTypeEnum? fromJson(dynamic value) => FunctionToolCallOutputTypeEnumTypeTransformer().decode(value);

  static List<FunctionToolCallOutputTypeEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionToolCallOutputTypeEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionToolCallOutputTypeEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FunctionToolCallOutputTypeEnum] to String,
/// and [decode] dynamic data back to [FunctionToolCallOutputTypeEnum].
class FunctionToolCallOutputTypeEnumTypeTransformer {
  factory FunctionToolCallOutputTypeEnumTypeTransformer() => _instance ??= const FunctionToolCallOutputTypeEnumTypeTransformer._();

  const FunctionToolCallOutputTypeEnumTypeTransformer._();

  String encode(FunctionToolCallOutputTypeEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FunctionToolCallOutputTypeEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FunctionToolCallOutputTypeEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'function_call_output': return FunctionToolCallOutputTypeEnum.functionCallOutput;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FunctionToolCallOutputTypeEnumTypeTransformer] instance.
  static FunctionToolCallOutputTypeEnumTypeTransformer? _instance;
}


/// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
class FunctionToolCallOutputStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const FunctionToolCallOutputStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const inProgress = FunctionToolCallOutputStatusEnum._(r'in_progress');
  static const completed = FunctionToolCallOutputStatusEnum._(r'completed');
  static const incomplete = FunctionToolCallOutputStatusEnum._(r'incomplete');

  /// List of all possible values in this [enum][FunctionToolCallOutputStatusEnum].
  static const values = <FunctionToolCallOutputStatusEnum>[
    inProgress,
    completed,
    incomplete,
  ];

  static FunctionToolCallOutputStatusEnum? fromJson(dynamic value) => FunctionToolCallOutputStatusEnumTypeTransformer().decode(value);

  static List<FunctionToolCallOutputStatusEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionToolCallOutputStatusEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionToolCallOutputStatusEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FunctionToolCallOutputStatusEnum] to String,
/// and [decode] dynamic data back to [FunctionToolCallOutputStatusEnum].
class FunctionToolCallOutputStatusEnumTypeTransformer {
  factory FunctionToolCallOutputStatusEnumTypeTransformer() => _instance ??= const FunctionToolCallOutputStatusEnumTypeTransformer._();

  const FunctionToolCallOutputStatusEnumTypeTransformer._();

  String encode(FunctionToolCallOutputStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FunctionToolCallOutputStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FunctionToolCallOutputStatusEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'in_progress': return FunctionToolCallOutputStatusEnum.inProgress;
        case r'completed': return FunctionToolCallOutputStatusEnum.completed;
        case r'incomplete': return FunctionToolCallOutputStatusEnum.incomplete;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FunctionToolCallOutputStatusEnumTypeTransformer] instance.
  static FunctionToolCallOutputStatusEnumTypeTransformer? _instance;
}


