//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class FunctionCallOutputItemParam {
  /// Returns a new [FunctionCallOutputItemParam] instance.
  FunctionCallOutputItemParam({
    this.id,
    required this.callId,
    this.type = const FunctionCallOutputItemParamTypeEnum._('function_call_output'),
    required this.output,
    this.status,
  });

  /// The unique ID of the function tool call output. Populated when this item is returned via API.
  String? id;

  /// The unique ID of the function tool call generated by the model.
  String callId;

  /// The type of the function tool call output. Always `function_call_output`.
  FunctionCallOutputItemParamTypeEnum type;

  /// A JSON string of the output of the function tool call.
  String output;

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  FunctionCallOutputItemParamStatusEnum? status;

  @override
  bool operator ==(Object other) => identical(this, other) || other is FunctionCallOutputItemParam &&
    other.id == id &&
    other.callId == callId &&
    other.type == type &&
    other.output == output &&
    other.status == status;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (id == null ? 0 : id!.hashCode) +
    (callId.hashCode) +
    (type.hashCode) +
    (output.hashCode) +
    (status == null ? 0 : status!.hashCode);

  @override
  String toString() => 'FunctionCallOutputItemParam[id=$id, callId=$callId, type=$type, output=$output, status=$status]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (this.id != null) {
      json[r'id'] = this.id;
    } else {
      json[r'id'] = null;
    }
      json[r'call_id'] = this.callId;
      json[r'type'] = this.type;
      json[r'output'] = this.output;
    if (this.status != null) {
      json[r'status'] = this.status;
    } else {
      json[r'status'] = null;
    }
    return json;
  }

  /// Returns a new [FunctionCallOutputItemParam] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static FunctionCallOutputItemParam? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "FunctionCallOutputItemParam[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "FunctionCallOutputItemParam[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return FunctionCallOutputItemParam(
        id: mapValueOfType<String>(json, r'id'),
        callId: mapValueOfType<String>(json, r'call_id')!,
        type: FunctionCallOutputItemParamTypeEnum.fromJson(json[r'type'])!,
        output: mapValueOfType<String>(json, r'output')!,
        status: FunctionCallOutputItemParamStatusEnum.fromJson(json[r'status']),
      );
    }
    return null;
  }

  static List<FunctionCallOutputItemParam> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionCallOutputItemParam>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionCallOutputItemParam.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, FunctionCallOutputItemParam> mapFromJson(dynamic json) {
    final map = <String, FunctionCallOutputItemParam>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = FunctionCallOutputItemParam.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of FunctionCallOutputItemParam-objects as value to a dart map
  static Map<String, List<FunctionCallOutputItemParam>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<FunctionCallOutputItemParam>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = FunctionCallOutputItemParam.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'call_id',
    'type',
    'output',
  };
}

/// The type of the function tool call output. Always `function_call_output`.
class FunctionCallOutputItemParamTypeEnum {
  /// Instantiate a new enum with the provided [value].
  const FunctionCallOutputItemParamTypeEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const functionCallOutput = FunctionCallOutputItemParamTypeEnum._(r'function_call_output');

  /// List of all possible values in this [enum][FunctionCallOutputItemParamTypeEnum].
  static const values = <FunctionCallOutputItemParamTypeEnum>[
    functionCallOutput,
  ];

  static FunctionCallOutputItemParamTypeEnum? fromJson(dynamic value) => FunctionCallOutputItemParamTypeEnumTypeTransformer().decode(value);

  static List<FunctionCallOutputItemParamTypeEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionCallOutputItemParamTypeEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionCallOutputItemParamTypeEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FunctionCallOutputItemParamTypeEnum] to String,
/// and [decode] dynamic data back to [FunctionCallOutputItemParamTypeEnum].
class FunctionCallOutputItemParamTypeEnumTypeTransformer {
  factory FunctionCallOutputItemParamTypeEnumTypeTransformer() => _instance ??= const FunctionCallOutputItemParamTypeEnumTypeTransformer._();

  const FunctionCallOutputItemParamTypeEnumTypeTransformer._();

  String encode(FunctionCallOutputItemParamTypeEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FunctionCallOutputItemParamTypeEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FunctionCallOutputItemParamTypeEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'function_call_output': return FunctionCallOutputItemParamTypeEnum.functionCallOutput;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FunctionCallOutputItemParamTypeEnumTypeTransformer] instance.
  static FunctionCallOutputItemParamTypeEnumTypeTransformer? _instance;
}


/// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
class FunctionCallOutputItemParamStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const FunctionCallOutputItemParamStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const inProgress = FunctionCallOutputItemParamStatusEnum._(r'in_progress');
  static const completed = FunctionCallOutputItemParamStatusEnum._(r'completed');
  static const incomplete = FunctionCallOutputItemParamStatusEnum._(r'incomplete');

  /// List of all possible values in this [enum][FunctionCallOutputItemParamStatusEnum].
  static const values = <FunctionCallOutputItemParamStatusEnum>[
    inProgress,
    completed,
    incomplete,
  ];

  static FunctionCallOutputItemParamStatusEnum? fromJson(dynamic value) => FunctionCallOutputItemParamStatusEnumTypeTransformer().decode(value);

  static List<FunctionCallOutputItemParamStatusEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionCallOutputItemParamStatusEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionCallOutputItemParamStatusEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FunctionCallOutputItemParamStatusEnum] to String,
/// and [decode] dynamic data back to [FunctionCallOutputItemParamStatusEnum].
class FunctionCallOutputItemParamStatusEnumTypeTransformer {
  factory FunctionCallOutputItemParamStatusEnumTypeTransformer() => _instance ??= const FunctionCallOutputItemParamStatusEnumTypeTransformer._();

  const FunctionCallOutputItemParamStatusEnumTypeTransformer._();

  String encode(FunctionCallOutputItemParamStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FunctionCallOutputItemParamStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FunctionCallOutputItemParamStatusEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'in_progress': return FunctionCallOutputItemParamStatusEnum.inProgress;
        case r'completed': return FunctionCallOutputItemParamStatusEnum.completed;
        case r'incomplete': return FunctionCallOutputItemParamStatusEnum.incomplete;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FunctionCallOutputItemParamStatusEnumTypeTransformer] instance.
  static FunctionCallOutputItemParamStatusEnumTypeTransformer? _instance;
}


