//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class FunctionToolCallResource {
  /// Returns a new [FunctionToolCallResource] instance.
  FunctionToolCallResource({
    required this.id,
    required this.type,
    required this.callId,
    required this.name,
    required this.arguments,
    this.status,
  });

  /// The unique ID of the function tool call. 
  String id;

  /// The type of the function tool call. Always `function_call`. 
  FunctionToolCallResourceTypeEnum type;

  /// The unique ID of the function tool call generated by the model. 
  String callId;

  /// The name of the function to run. 
  String name;

  /// A JSON string of the arguments to pass to the function. 
  String arguments;

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
  FunctionToolCallResourceStatusEnum? status;

  @override
  bool operator ==(Object other) => identical(this, other) || other is FunctionToolCallResource &&
    other.id == id &&
    other.type == type &&
    other.callId == callId &&
    other.name == name &&
    other.arguments == arguments &&
    other.status == status;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (id.hashCode) +
    (type.hashCode) +
    (callId.hashCode) +
    (name.hashCode) +
    (arguments.hashCode) +
    (status == null ? 0 : status!.hashCode);

  @override
  String toString() => 'FunctionToolCallResource[id=$id, type=$type, callId=$callId, name=$name, arguments=$arguments, status=$status]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'id'] = this.id;
      json[r'type'] = this.type;
      json[r'call_id'] = this.callId;
      json[r'name'] = this.name;
      json[r'arguments'] = this.arguments;
    if (this.status != null) {
      json[r'status'] = this.status;
    } else {
      json[r'status'] = null;
    }
    return json;
  }

  /// Returns a new [FunctionToolCallResource] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static FunctionToolCallResource? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "FunctionToolCallResource[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "FunctionToolCallResource[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return FunctionToolCallResource(
        id: mapValueOfType<String>(json, r'id')!,
        type: FunctionToolCallResourceTypeEnum.fromJson(json[r'type'])!,
        callId: mapValueOfType<String>(json, r'call_id')!,
        name: mapValueOfType<String>(json, r'name')!,
        arguments: mapValueOfType<String>(json, r'arguments')!,
        status: FunctionToolCallResourceStatusEnum.fromJson(json[r'status']),
      );
    }
    return null;
  }

  static List<FunctionToolCallResource> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionToolCallResource>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionToolCallResource.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, FunctionToolCallResource> mapFromJson(dynamic json) {
    final map = <String, FunctionToolCallResource>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = FunctionToolCallResource.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of FunctionToolCallResource-objects as value to a dart map
  static Map<String, List<FunctionToolCallResource>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<FunctionToolCallResource>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = FunctionToolCallResource.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'id',
    'type',
    'call_id',
    'name',
    'arguments',
  };
}

/// The type of the function tool call. Always `function_call`. 
class FunctionToolCallResourceTypeEnum {
  /// Instantiate a new enum with the provided [value].
  const FunctionToolCallResourceTypeEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const functionCall = FunctionToolCallResourceTypeEnum._(r'function_call');

  /// List of all possible values in this [enum][FunctionToolCallResourceTypeEnum].
  static const values = <FunctionToolCallResourceTypeEnum>[
    functionCall,
  ];

  static FunctionToolCallResourceTypeEnum? fromJson(dynamic value) => FunctionToolCallResourceTypeEnumTypeTransformer().decode(value);

  static List<FunctionToolCallResourceTypeEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionToolCallResourceTypeEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionToolCallResourceTypeEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FunctionToolCallResourceTypeEnum] to String,
/// and [decode] dynamic data back to [FunctionToolCallResourceTypeEnum].
class FunctionToolCallResourceTypeEnumTypeTransformer {
  factory FunctionToolCallResourceTypeEnumTypeTransformer() => _instance ??= const FunctionToolCallResourceTypeEnumTypeTransformer._();

  const FunctionToolCallResourceTypeEnumTypeTransformer._();

  String encode(FunctionToolCallResourceTypeEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FunctionToolCallResourceTypeEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FunctionToolCallResourceTypeEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'function_call': return FunctionToolCallResourceTypeEnum.functionCall;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FunctionToolCallResourceTypeEnumTypeTransformer] instance.
  static FunctionToolCallResourceTypeEnumTypeTransformer? _instance;
}


/// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. 
class FunctionToolCallResourceStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const FunctionToolCallResourceStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const inProgress = FunctionToolCallResourceStatusEnum._(r'in_progress');
  static const completed = FunctionToolCallResourceStatusEnum._(r'completed');
  static const incomplete = FunctionToolCallResourceStatusEnum._(r'incomplete');

  /// List of all possible values in this [enum][FunctionToolCallResourceStatusEnum].
  static const values = <FunctionToolCallResourceStatusEnum>[
    inProgress,
    completed,
    incomplete,
  ];

  static FunctionToolCallResourceStatusEnum? fromJson(dynamic value) => FunctionToolCallResourceStatusEnumTypeTransformer().decode(value);

  static List<FunctionToolCallResourceStatusEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <FunctionToolCallResourceStatusEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FunctionToolCallResourceStatusEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [FunctionToolCallResourceStatusEnum] to String,
/// and [decode] dynamic data back to [FunctionToolCallResourceStatusEnum].
class FunctionToolCallResourceStatusEnumTypeTransformer {
  factory FunctionToolCallResourceStatusEnumTypeTransformer() => _instance ??= const FunctionToolCallResourceStatusEnumTypeTransformer._();

  const FunctionToolCallResourceStatusEnumTypeTransformer._();

  String encode(FunctionToolCallResourceStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a FunctionToolCallResourceStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  FunctionToolCallResourceStatusEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'in_progress': return FunctionToolCallResourceStatusEnum.inProgress;
        case r'completed': return FunctionToolCallResourceStatusEnum.completed;
        case r'incomplete': return FunctionToolCallResourceStatusEnum.incomplete;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [FunctionToolCallResourceStatusEnumTypeTransformer] instance.
  static FunctionToolCallResourceStatusEnumTypeTransformer? _instance;
}


