//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class Item {
  /// Returns a new [Item] instance.
  Item({
    required this.type,
    required this.role,
    required this.status,
    this.content = const [],
    required this.id,
    this.queries = const [],
    this.results = const [],
    required this.callId,
    required this.action,
    this.pendingSafetyChecks = const [],
    required this.output,
    this.acknowledgedSafetyChecks = const [],
    required this.name,
    required this.arguments,
    this.encryptedContent,
    this.summary = const [],
    required this.result,
    required this.containerId,
    required this.code,
    this.outputs = const [],
    required this.serverLabel,
    this.tools = const [],
    this.error,
    required this.approvalRequestId,
    required this.approve,
    this.reason,
  });

  /// The type of the message input. Always set to `message`. 
  ItemTypeEnum type;

  /// The role of the output message. Always `assistant`. 
  ItemRoleEnum role;

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. 
  ItemStatusEnum status;

  /// The content of the output message. 
  List<OutputContent> content;

  /// The unique ID of the tool call. 
  String id;

  /// The queries used to search for files. 
  List<String> queries;

  /// The results of the file search tool call. 
  List<FileSearchToolCallResultsInner> results;

  /// The unique ID of the local shell tool call generated by the model. 
  String callId;

  LocalShellExecAction action;

  /// The pending safety checks for the computer call. 
  List<ComputerToolCallSafetyCheck> pendingSafetyChecks;

  /// The output from the tool call. 
  String output;

  /// The safety checks reported by the API that have been acknowledged by the developer.
  List<ComputerCallSafetyCheckParam> acknowledgedSafetyChecks;

  /// The name of the tool that was run. 
  String name;

  /// A JSON string of the arguments passed to the tool. 
  String arguments;

  /// The encrypted content of the reasoning item - populated when a response is generated with `reasoning.encrypted_content` in the `include` parameter. 
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? encryptedContent;

  /// Reasoning text contents. 
  List<ReasoningItemSummaryInner> summary;

  /// The generated image encoded in base64. 
  String result;

  /// The ID of the container used to run the code. 
  String containerId;

  /// The code to run, or null if not available. 
  String code;

  /// The outputs generated by the code interpreter, such as logs or images.  Can be null if no outputs are available. 
  List<CodeInterpreterToolCallOutputsInner> outputs;

  /// The label of the MCP server running the tool. 
  String serverLabel;

  /// The tools available on the server. 
  List<MCPListToolsTool> tools;

  /// The error from the tool call, if any. 
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? error;

  /// The ID of the approval request being answered. 
  String approvalRequestId;

  /// Whether the request was approved. 
  bool approve;

  /// Optional reason for the decision. 
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? reason;

  @override
  bool operator ==(Object other) => identical(this, other) || other is Item &&
    other.type == type &&
    other.role == role &&
    other.status == status &&
    _deepEquality.equals(other.content, content) &&
    other.id == id &&
    _deepEquality.equals(other.queries, queries) &&
    _deepEquality.equals(other.results, results) &&
    other.callId == callId &&
    other.action == action &&
    _deepEquality.equals(other.pendingSafetyChecks, pendingSafetyChecks) &&
    other.output == output &&
    _deepEquality.equals(other.acknowledgedSafetyChecks, acknowledgedSafetyChecks) &&
    other.name == name &&
    other.arguments == arguments &&
    other.encryptedContent == encryptedContent &&
    _deepEquality.equals(other.summary, summary) &&
    other.result == result &&
    other.containerId == containerId &&
    other.code == code &&
    _deepEquality.equals(other.outputs, outputs) &&
    other.serverLabel == serverLabel &&
    _deepEquality.equals(other.tools, tools) &&
    other.error == error &&
    other.approvalRequestId == approvalRequestId &&
    other.approve == approve &&
    other.reason == reason;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (type.hashCode) +
    (role.hashCode) +
    (status.hashCode) +
    (content.hashCode) +
    (id.hashCode) +
    (queries.hashCode) +
    (results.hashCode) +
    (callId.hashCode) +
    (action.hashCode) +
    (pendingSafetyChecks.hashCode) +
    (output.hashCode) +
    (acknowledgedSafetyChecks.hashCode) +
    (name.hashCode) +
    (arguments.hashCode) +
    (encryptedContent == null ? 0 : encryptedContent!.hashCode) +
    (summary.hashCode) +
    (result.hashCode) +
    (containerId.hashCode) +
    (code.hashCode) +
    (outputs.hashCode) +
    (serverLabel.hashCode) +
    (tools.hashCode) +
    (error == null ? 0 : error!.hashCode) +
    (approvalRequestId.hashCode) +
    (approve.hashCode) +
    (reason == null ? 0 : reason!.hashCode);

  @override
  String toString() => 'Item[type=$type, role=$role, status=$status, content=$content, id=$id, queries=$queries, results=$results, callId=$callId, action=$action, pendingSafetyChecks=$pendingSafetyChecks, output=$output, acknowledgedSafetyChecks=$acknowledgedSafetyChecks, name=$name, arguments=$arguments, encryptedContent=$encryptedContent, summary=$summary, result=$result, containerId=$containerId, code=$code, outputs=$outputs, serverLabel=$serverLabel, tools=$tools, error=$error, approvalRequestId=$approvalRequestId, approve=$approve, reason=$reason]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'type'] = this.type;
      json[r'role'] = this.role;
      json[r'status'] = this.status;
      json[r'content'] = this.content;
      json[r'id'] = this.id;
      json[r'queries'] = this.queries;
      json[r'results'] = this.results;
      json[r'call_id'] = this.callId;
      json[r'action'] = this.action;
      json[r'pending_safety_checks'] = this.pendingSafetyChecks;
      json[r'output'] = this.output;
      json[r'acknowledged_safety_checks'] = this.acknowledgedSafetyChecks;
      json[r'name'] = this.name;
      json[r'arguments'] = this.arguments;
    if (this.encryptedContent != null) {
      json[r'encrypted_content'] = this.encryptedContent;
    } else {
      json[r'encrypted_content'] = null;
    }
      json[r'summary'] = this.summary;
      json[r'result'] = this.result;
      json[r'container_id'] = this.containerId;
      json[r'code'] = this.code;
      json[r'outputs'] = this.outputs;
      json[r'server_label'] = this.serverLabel;
      json[r'tools'] = this.tools;
    if (this.error != null) {
      json[r'error'] = this.error;
    } else {
      json[r'error'] = null;
    }
      json[r'approval_request_id'] = this.approvalRequestId;
      json[r'approve'] = this.approve;
    if (this.reason != null) {
      json[r'reason'] = this.reason;
    } else {
      json[r'reason'] = null;
    }
    return json;
  }

  /// Returns a new [Item] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static Item? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "Item[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "Item[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return Item(
        type: ItemTypeEnum.fromJson(json[r'type'])!,
        role: ItemRoleEnum.fromJson(json[r'role'])!,
        status: ItemStatusEnum.fromJson(json[r'status'])!,
        content: OutputContent.listFromJson(json[r'content']),
        id: mapValueOfType<String>(json, r'id')!,
        queries: json[r'queries'] is Iterable
            ? (json[r'queries'] as Iterable).cast<String>().toList(growable: false)
            : const [],
        results: FileSearchToolCallResultsInner.listFromJson(json[r'results']),
        callId: mapValueOfType<String>(json, r'call_id')!,
        action: LocalShellExecAction.fromJson(json[r'action'])!,
        pendingSafetyChecks: ComputerToolCallSafetyCheck.listFromJson(json[r'pending_safety_checks']),
        output: mapValueOfType<String>(json, r'output')!,
        acknowledgedSafetyChecks: ComputerCallSafetyCheckParam.listFromJson(json[r'acknowledged_safety_checks']),
        name: mapValueOfType<String>(json, r'name')!,
        arguments: mapValueOfType<String>(json, r'arguments')!,
        encryptedContent: mapValueOfType<String>(json, r'encrypted_content'),
        summary: ReasoningItemSummaryInner.listFromJson(json[r'summary']),
        result: mapValueOfType<String>(json, r'result')!,
        containerId: mapValueOfType<String>(json, r'container_id')!,
        code: mapValueOfType<String>(json, r'code')!,
        outputs: CodeInterpreterToolCallOutputsInner.listFromJson(json[r'outputs']),
        serverLabel: mapValueOfType<String>(json, r'server_label')!,
        tools: MCPListToolsTool.listFromJson(json[r'tools']),
        error: mapValueOfType<String>(json, r'error'),
        approvalRequestId: mapValueOfType<String>(json, r'approval_request_id')!,
        approve: mapValueOfType<bool>(json, r'approve')!,
        reason: mapValueOfType<String>(json, r'reason'),
      );
    }
    return null;
  }

  static List<Item> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <Item>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = Item.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, Item> mapFromJson(dynamic json) {
    final map = <String, Item>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = Item.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of Item-objects as value to a dart map
  static Map<String, List<Item>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<Item>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = Item.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'type',
    'role',
    'status',
    'content',
    'id',
    'queries',
    'call_id',
    'action',
    'pending_safety_checks',
    'output',
    'name',
    'arguments',
    'summary',
    'result',
    'container_id',
    'code',
    'outputs',
    'server_label',
    'tools',
    'approval_request_id',
    'approve',
  };
}

/// The type of the message input. Always set to `message`. 
class ItemTypeEnum {
  /// Instantiate a new enum with the provided [value].
  const ItemTypeEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const message = ItemTypeEnum._(r'message');
  static const fileSearchCall = ItemTypeEnum._(r'file_search_call');
  static const computerCall = ItemTypeEnum._(r'computer_call');
  static const computerCallOutput = ItemTypeEnum._(r'computer_call_output');
  static const webSearchCall = ItemTypeEnum._(r'web_search_call');
  static const functionCall = ItemTypeEnum._(r'function_call');
  static const functionCallOutput = ItemTypeEnum._(r'function_call_output');
  static const reasoning = ItemTypeEnum._(r'reasoning');
  static const imageGenerationCall = ItemTypeEnum._(r'image_generation_call');
  static const codeInterpreterCall = ItemTypeEnum._(r'code_interpreter_call');
  static const localShellCall = ItemTypeEnum._(r'local_shell_call');
  static const localShellCallOutput = ItemTypeEnum._(r'local_shell_call_output');
  static const mcpListTools = ItemTypeEnum._(r'mcp_list_tools');
  static const mcpApprovalRequest = ItemTypeEnum._(r'mcp_approval_request');
  static const mcpApprovalResponse = ItemTypeEnum._(r'mcp_approval_response');
  static const mcpCall = ItemTypeEnum._(r'mcp_call');

  /// List of all possible values in this [enum][ItemTypeEnum].
  static const values = <ItemTypeEnum>[
    message,
    fileSearchCall,
    computerCall,
    computerCallOutput,
    webSearchCall,
    functionCall,
    functionCallOutput,
    reasoning,
    imageGenerationCall,
    codeInterpreterCall,
    localShellCall,
    localShellCallOutput,
    mcpListTools,
    mcpApprovalRequest,
    mcpApprovalResponse,
    mcpCall,
  ];

  static ItemTypeEnum? fromJson(dynamic value) => ItemTypeEnumTypeTransformer().decode(value);

  static List<ItemTypeEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <ItemTypeEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = ItemTypeEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [ItemTypeEnum] to String,
/// and [decode] dynamic data back to [ItemTypeEnum].
class ItemTypeEnumTypeTransformer {
  factory ItemTypeEnumTypeTransformer() => _instance ??= const ItemTypeEnumTypeTransformer._();

  const ItemTypeEnumTypeTransformer._();

  String encode(ItemTypeEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a ItemTypeEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  ItemTypeEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'message': return ItemTypeEnum.message;
        case r'file_search_call': return ItemTypeEnum.fileSearchCall;
        case r'computer_call': return ItemTypeEnum.computerCall;
        case r'computer_call_output': return ItemTypeEnum.computerCallOutput;
        case r'web_search_call': return ItemTypeEnum.webSearchCall;
        case r'function_call': return ItemTypeEnum.functionCall;
        case r'function_call_output': return ItemTypeEnum.functionCallOutput;
        case r'reasoning': return ItemTypeEnum.reasoning;
        case r'image_generation_call': return ItemTypeEnum.imageGenerationCall;
        case r'code_interpreter_call': return ItemTypeEnum.codeInterpreterCall;
        case r'local_shell_call': return ItemTypeEnum.localShellCall;
        case r'local_shell_call_output': return ItemTypeEnum.localShellCallOutput;
        case r'mcp_list_tools': return ItemTypeEnum.mcpListTools;
        case r'mcp_approval_request': return ItemTypeEnum.mcpApprovalRequest;
        case r'mcp_approval_response': return ItemTypeEnum.mcpApprovalResponse;
        case r'mcp_call': return ItemTypeEnum.mcpCall;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [ItemTypeEnumTypeTransformer] instance.
  static ItemTypeEnumTypeTransformer? _instance;
}


/// The role of the output message. Always `assistant`. 
class ItemRoleEnum {
  /// Instantiate a new enum with the provided [value].
  const ItemRoleEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const assistant = ItemRoleEnum._(r'assistant');

  /// List of all possible values in this [enum][ItemRoleEnum].
  static const values = <ItemRoleEnum>[
    assistant,
  ];

  static ItemRoleEnum? fromJson(dynamic value) => ItemRoleEnumTypeTransformer().decode(value);

  static List<ItemRoleEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <ItemRoleEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = ItemRoleEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [ItemRoleEnum] to String,
/// and [decode] dynamic data back to [ItemRoleEnum].
class ItemRoleEnumTypeTransformer {
  factory ItemRoleEnumTypeTransformer() => _instance ??= const ItemRoleEnumTypeTransformer._();

  const ItemRoleEnumTypeTransformer._();

  String encode(ItemRoleEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a ItemRoleEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  ItemRoleEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'assistant': return ItemRoleEnum.assistant;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [ItemRoleEnumTypeTransformer] instance.
  static ItemRoleEnumTypeTransformer? _instance;
}


/// The status of the item. One of `in_progress`, `completed`, or `incomplete`. 
class ItemStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const ItemStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const inProgress = ItemStatusEnum._(r'in_progress');
  static const completed = ItemStatusEnum._(r'completed');
  static const incomplete = ItemStatusEnum._(r'incomplete');

  /// List of all possible values in this [enum][ItemStatusEnum].
  static const values = <ItemStatusEnum>[
    inProgress,
    completed,
    incomplete,
  ];

  static ItemStatusEnum? fromJson(dynamic value) => ItemStatusEnumTypeTransformer().decode(value);

  static List<ItemStatusEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <ItemStatusEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = ItemStatusEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [ItemStatusEnum] to String,
/// and [decode] dynamic data back to [ItemStatusEnum].
class ItemStatusEnumTypeTransformer {
  factory ItemStatusEnumTypeTransformer() => _instance ??= const ItemStatusEnumTypeTransformer._();

  const ItemStatusEnumTypeTransformer._();

  String encode(ItemStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a ItemStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  ItemStatusEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'in_progress': return ItemStatusEnum.inProgress;
        case r'completed': return ItemStatusEnum.completed;
        case r'incomplete': return ItemStatusEnum.incomplete;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [ItemStatusEnumTypeTransformer] instance.
  static ItemStatusEnumTypeTransformer? _instance;
}


