//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class LocalShellToolCallOutput {
  /// Returns a new [LocalShellToolCallOutput] instance.
  LocalShellToolCallOutput({
    required this.type,
    required this.id,
    required this.output,
    this.status,
  });

  /// The type of the local shell tool call output. Always `local_shell_call_output`. 
  LocalShellToolCallOutputTypeEnum type;

  /// The unique ID of the local shell tool call generated by the model. 
  String id;

  /// A JSON string of the output of the local shell tool call. 
  String output;

  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. 
  LocalShellToolCallOutputStatusEnum? status;

  @override
  bool operator ==(Object other) => identical(this, other) || other is LocalShellToolCallOutput &&
    other.type == type &&
    other.id == id &&
    other.output == output &&
    other.status == status;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (type.hashCode) +
    (id.hashCode) +
    (output.hashCode) +
    (status == null ? 0 : status!.hashCode);

  @override
  String toString() => 'LocalShellToolCallOutput[type=$type, id=$id, output=$output, status=$status]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'type'] = this.type;
      json[r'id'] = this.id;
      json[r'output'] = this.output;
    if (this.status != null) {
      json[r'status'] = this.status;
    } else {
      json[r'status'] = null;
    }
    return json;
  }

  /// Returns a new [LocalShellToolCallOutput] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static LocalShellToolCallOutput? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "LocalShellToolCallOutput[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "LocalShellToolCallOutput[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return LocalShellToolCallOutput(
        type: LocalShellToolCallOutputTypeEnum.fromJson(json[r'type'])!,
        id: mapValueOfType<String>(json, r'id')!,
        output: mapValueOfType<String>(json, r'output')!,
        status: LocalShellToolCallOutputStatusEnum.fromJson(json[r'status']),
      );
    }
    return null;
  }

  static List<LocalShellToolCallOutput> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <LocalShellToolCallOutput>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LocalShellToolCallOutput.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, LocalShellToolCallOutput> mapFromJson(dynamic json) {
    final map = <String, LocalShellToolCallOutput>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = LocalShellToolCallOutput.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of LocalShellToolCallOutput-objects as value to a dart map
  static Map<String, List<LocalShellToolCallOutput>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<LocalShellToolCallOutput>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = LocalShellToolCallOutput.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'type',
    'id',
    'output',
  };
}

/// The type of the local shell tool call output. Always `local_shell_call_output`. 
class LocalShellToolCallOutputTypeEnum {
  /// Instantiate a new enum with the provided [value].
  const LocalShellToolCallOutputTypeEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const localShellCallOutput = LocalShellToolCallOutputTypeEnum._(r'local_shell_call_output');

  /// List of all possible values in this [enum][LocalShellToolCallOutputTypeEnum].
  static const values = <LocalShellToolCallOutputTypeEnum>[
    localShellCallOutput,
  ];

  static LocalShellToolCallOutputTypeEnum? fromJson(dynamic value) => LocalShellToolCallOutputTypeEnumTypeTransformer().decode(value);

  static List<LocalShellToolCallOutputTypeEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <LocalShellToolCallOutputTypeEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LocalShellToolCallOutputTypeEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [LocalShellToolCallOutputTypeEnum] to String,
/// and [decode] dynamic data back to [LocalShellToolCallOutputTypeEnum].
class LocalShellToolCallOutputTypeEnumTypeTransformer {
  factory LocalShellToolCallOutputTypeEnumTypeTransformer() => _instance ??= const LocalShellToolCallOutputTypeEnumTypeTransformer._();

  const LocalShellToolCallOutputTypeEnumTypeTransformer._();

  String encode(LocalShellToolCallOutputTypeEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a LocalShellToolCallOutputTypeEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  LocalShellToolCallOutputTypeEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'local_shell_call_output': return LocalShellToolCallOutputTypeEnum.localShellCallOutput;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [LocalShellToolCallOutputTypeEnumTypeTransformer] instance.
  static LocalShellToolCallOutputTypeEnumTypeTransformer? _instance;
}


/// The status of the item. One of `in_progress`, `completed`, or `incomplete`. 
class LocalShellToolCallOutputStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const LocalShellToolCallOutputStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const inProgress = LocalShellToolCallOutputStatusEnum._(r'in_progress');
  static const completed = LocalShellToolCallOutputStatusEnum._(r'completed');
  static const incomplete = LocalShellToolCallOutputStatusEnum._(r'incomplete');

  /// List of all possible values in this [enum][LocalShellToolCallOutputStatusEnum].
  static const values = <LocalShellToolCallOutputStatusEnum>[
    inProgress,
    completed,
    incomplete,
  ];

  static LocalShellToolCallOutputStatusEnum? fromJson(dynamic value) => LocalShellToolCallOutputStatusEnumTypeTransformer().decode(value);

  static List<LocalShellToolCallOutputStatusEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <LocalShellToolCallOutputStatusEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LocalShellToolCallOutputStatusEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [LocalShellToolCallOutputStatusEnum] to String,
/// and [decode] dynamic data back to [LocalShellToolCallOutputStatusEnum].
class LocalShellToolCallOutputStatusEnumTypeTransformer {
  factory LocalShellToolCallOutputStatusEnumTypeTransformer() => _instance ??= const LocalShellToolCallOutputStatusEnumTypeTransformer._();

  const LocalShellToolCallOutputStatusEnumTypeTransformer._();

  String encode(LocalShellToolCallOutputStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a LocalShellToolCallOutputStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  LocalShellToolCallOutputStatusEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'in_progress': return LocalShellToolCallOutputStatusEnum.inProgress;
        case r'completed': return LocalShellToolCallOutputStatusEnum.completed;
        case r'incomplete': return LocalShellToolCallOutputStatusEnum.incomplete;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [LocalShellToolCallOutputStatusEnumTypeTransformer] instance.
  static LocalShellToolCallOutputStatusEnumTypeTransformer? _instance;
}


