//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class LocalShellToolCall {
  /// Returns a new [LocalShellToolCall] instance.
  LocalShellToolCall({
    required this.type,
    required this.id,
    required this.callId,
    required this.action,
    required this.status,
  });

  /// The type of the local shell call. Always `local_shell_call`. 
  LocalShellToolCallTypeEnum type;

  /// The unique ID of the local shell call. 
  String id;

  /// The unique ID of the local shell tool call generated by the model. 
  String callId;

  LocalShellExecAction action;

  /// The status of the local shell call. 
  LocalShellToolCallStatusEnum status;

  @override
  bool operator ==(Object other) => identical(this, other) || other is LocalShellToolCall &&
    other.type == type &&
    other.id == id &&
    other.callId == callId &&
    other.action == action &&
    other.status == status;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (type.hashCode) +
    (id.hashCode) +
    (callId.hashCode) +
    (action.hashCode) +
    (status.hashCode);

  @override
  String toString() => 'LocalShellToolCall[type=$type, id=$id, callId=$callId, action=$action, status=$status]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'type'] = this.type;
      json[r'id'] = this.id;
      json[r'call_id'] = this.callId;
      json[r'action'] = this.action;
      json[r'status'] = this.status;
    return json;
  }

  /// Returns a new [LocalShellToolCall] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static LocalShellToolCall? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "LocalShellToolCall[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "LocalShellToolCall[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return LocalShellToolCall(
        type: LocalShellToolCallTypeEnum.fromJson(json[r'type'])!,
        id: mapValueOfType<String>(json, r'id')!,
        callId: mapValueOfType<String>(json, r'call_id')!,
        action: LocalShellExecAction.fromJson(json[r'action'])!,
        status: LocalShellToolCallStatusEnum.fromJson(json[r'status'])!,
      );
    }
    return null;
  }

  static List<LocalShellToolCall> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <LocalShellToolCall>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LocalShellToolCall.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, LocalShellToolCall> mapFromJson(dynamic json) {
    final map = <String, LocalShellToolCall>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = LocalShellToolCall.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of LocalShellToolCall-objects as value to a dart map
  static Map<String, List<LocalShellToolCall>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<LocalShellToolCall>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = LocalShellToolCall.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'type',
    'id',
    'call_id',
    'action',
    'status',
  };
}

/// The type of the local shell call. Always `local_shell_call`. 
class LocalShellToolCallTypeEnum {
  /// Instantiate a new enum with the provided [value].
  const LocalShellToolCallTypeEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const localShellCall = LocalShellToolCallTypeEnum._(r'local_shell_call');

  /// List of all possible values in this [enum][LocalShellToolCallTypeEnum].
  static const values = <LocalShellToolCallTypeEnum>[
    localShellCall,
  ];

  static LocalShellToolCallTypeEnum? fromJson(dynamic value) => LocalShellToolCallTypeEnumTypeTransformer().decode(value);

  static List<LocalShellToolCallTypeEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <LocalShellToolCallTypeEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LocalShellToolCallTypeEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [LocalShellToolCallTypeEnum] to String,
/// and [decode] dynamic data back to [LocalShellToolCallTypeEnum].
class LocalShellToolCallTypeEnumTypeTransformer {
  factory LocalShellToolCallTypeEnumTypeTransformer() => _instance ??= const LocalShellToolCallTypeEnumTypeTransformer._();

  const LocalShellToolCallTypeEnumTypeTransformer._();

  String encode(LocalShellToolCallTypeEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a LocalShellToolCallTypeEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  LocalShellToolCallTypeEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'local_shell_call': return LocalShellToolCallTypeEnum.localShellCall;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [LocalShellToolCallTypeEnumTypeTransformer] instance.
  static LocalShellToolCallTypeEnumTypeTransformer? _instance;
}


/// The status of the local shell call. 
class LocalShellToolCallStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const LocalShellToolCallStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const inProgress = LocalShellToolCallStatusEnum._(r'in_progress');
  static const completed = LocalShellToolCallStatusEnum._(r'completed');
  static const incomplete = LocalShellToolCallStatusEnum._(r'incomplete');

  /// List of all possible values in this [enum][LocalShellToolCallStatusEnum].
  static const values = <LocalShellToolCallStatusEnum>[
    inProgress,
    completed,
    incomplete,
  ];

  static LocalShellToolCallStatusEnum? fromJson(dynamic value) => LocalShellToolCallStatusEnumTypeTransformer().decode(value);

  static List<LocalShellToolCallStatusEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <LocalShellToolCallStatusEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LocalShellToolCallStatusEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [LocalShellToolCallStatusEnum] to String,
/// and [decode] dynamic data back to [LocalShellToolCallStatusEnum].
class LocalShellToolCallStatusEnumTypeTransformer {
  factory LocalShellToolCallStatusEnumTypeTransformer() => _instance ??= const LocalShellToolCallStatusEnumTypeTransformer._();

  const LocalShellToolCallStatusEnumTypeTransformer._();

  String encode(LocalShellToolCallStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a LocalShellToolCallStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  LocalShellToolCallStatusEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'in_progress': return LocalShellToolCallStatusEnum.inProgress;
        case r'completed': return LocalShellToolCallStatusEnum.completed;
        case r'incomplete': return LocalShellToolCallStatusEnum.incomplete;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [LocalShellToolCallStatusEnumTypeTransformer] instance.
  static LocalShellToolCallStatusEnumTypeTransformer? _instance;
}


